export const colleges = [
	"Alabama A&M University",
	"Alabama State University",
	"Athens State University",
	"Auburn University",
	"Auburn University at Montgomery",
	"Bevill State Community College",
	"Birmingham-Southern College",
	"Calhoun Community College",
	"Central Alabama Community College",
	"Enterprise State Community College",
	"Gadsden State Community College",
	"Huntingdon College",
	"Jacksonville State University",
	"Lurleen B. Wallace Community College",
	"Marion Military Institute",
	"Miles College",
	"Samford University",
	"Snead State Community College",
	"Southern Union State Community College",
	"Spring Hill College",
	"Troy University",
	"Troy University Dothan",
	"Troy University Montgomery",
	"Troy University Phenix City",
	"Tuskegee University",
	"University of Alabama",
	"University of Alabama at Birmingham",
	"University of Alabama in Huntsville",
	"University of Montevallo",
	"University of North Alabama",
	"University of South Alabama",
	"University of West Alabama",
	"Ilisagvik College",
	"University of Alaska Anchorage",
	"University of Alaska Fairbanks",
	"University of Alaska Southeast",
	"American Samoa Community College",
	"Arizona State University",
	"Arizona Western College",
	"Dine College",
	"Embry-Riddle Aeronautical University at Prescott",
	"Grand Canyon University",
	"Midwestern University at Glendale",
	"Mohave Community College",
	"Northern Arizona University",
	"University of Arizona",
	"Arkansas Northeastern College",
	"Arkansas State University",
	"Arkansas State University-Newport",
	"Arkansas Tech University",
	"Black River Technical College",
	"Central Baptist College",
	"Cossatot Community College of the University of Arkansas",
	"Harding University",
	"Henderson State University",
	"Hendrix College",
	"John Brown University",
	"Lyon College",
	"National Park College",
	"North Arkansas College",
	"NorthWest Arkansas Community College",
	"Ouachita Baptist University",
	"South Arkansas Community College",
	"Southern Arkansas University",
	"University of Arkansas",
	"University of Arkansas-Pulaski Technical College",
	"University of Central Arkansas",
	"University of the Ozarks",
	"Academy of Art University",
	"Antelope Valley College",
	"Azusa Pacific University",
	"Bakersfield College",
	"Biola University",
	"California Baptist University",
	"California Institute of Technology",
	"California Lutheran University",
	"California State Polytechnic University",
	"California State Polytechnic University",
	"California State University",
	"Chapman University",
	"Claremont McKenna College",
	"Concordia University Irvine",
	"Cypress College",
	"Dominican University of California",
	"El Camino Community College",
	"Feather River College",
	"Foothill College",
	"Fresno Pacific University",
	"Fresno State University",
	"Harvey Mudd College",
	"Holy Names University",
	"Humboldt State University",
	"Los Angeles Community College District",
	"Loyola Marymount University",
	"Menlo College",
	"Mills College",
	"MiraCosta College",
	"Modesto Junior College",
	"Naval Postgraduate School",
	"Notre Dame de Namur University",
	"Occidental College",
	"Pepperdine University",
	"Pitzer College",
	"Point Loma Nazarene University",
	"Pomona College",
	"Rio Hondo College",
	"Saint Mary's College of California",
	"San Diego City College",
	"San Diego Mesa College",
	"San Diego Miramar College",
	"San Diego State University System",
	"San Francisco State University",
	"San Jose State University",
	"Santa Ana College",
	"Santa Clara University",
	"Santa Monica College",
	"Santiago Canyon College",
	"Scripps College",
	"Shasta College",
	"Skyline College",
	"Solano Community College",
	"Sonoma State University",
	"Southwestern College",
	"Stanford University",
	"Teachers College of San Joaquin",
	"University of California, Berkeley",
	"University of California, Davis",
	"University of California, Hastings College of Law",
	"University of California, Irvine",
	"University of California, Los Angeles",
	"University of California, Merced",
	"University of California, Riverside",
	"University of California, San Diego",
	"University of California, San Francisco",
	"University of California, Santa Barbara",
	"University of California, Santa Cruz",
	"University of La Verne",
	"University of Redlands",
	"University of San Diego",
	"University of San Francisco",
	"University of Southern California",
	"University of the Pacific",
	"Westmont College",
	"Whittier College",
	"Adams State University",
	"Arapahoe Community College",
	"Colorado Christian University",
	"Colorado College",
	"Colorado Mesa University",
	"Colorado Mountain College Glenwood Springs",
	"Colorado School of Mines",
	"Colorado State University",
	"Colorado State University-Pueblo",
	"Community College of Aurora",
	"Community College of Denver",
	"Fort Lewis College",
	"Front Range Community College",
	"Johnson & Wales University-Denver",
	"Lamar Community College",
	"Metropolitan State University of Denver",
	"Morgan Community College",
	"Northeastern Junior College",
	"Otero Junior College",
	"Pikes Peak Community College",
	"Pueblo Community College",
	"Red Rocks Community College",
	"Regis University",
	"Trinidad State Junior College",
	"United States Air Force Academy",
	"University of Colorado Boulder",
	"University of Colorado Colorado Springs",
	"University of Colorado Denver and Anschutz Medical Campus",
	"University of Denver",
	"University of Northern Colorado",
	"Western Colorado University",
	"Albertus Magnus College",
	"Central Connecticut State University",
	"Connecticut College",
	"Eastern Connecticut State University",
	"Fairfield University",
	"Mitchell College",
	"Post University",
	"Quinnipiac University",
	"Sacred Heart University",
	"Southern Connecticut State University",
	"Trinity College",
	"Tunxis Community College",
	"United States Coast Guard Academy",
	"University of Bridgeport",
	"University of Connecticut",
	"University of Hartford",
	"University of New Haven",
	"University of Saint Joseph",
	"Wesleyan University",
	"Western Connecticut State University",
	"Yale University",
	"Delaware State University",
	"Delaware Technical Community College Dover",
	"Delaware Technical Community College Georgetown",
	"Delaware Technical Community College Stanton",
	"Goldey-Beacom College",
	"University of Delaware",
	"Wesley College",
	"Wilmington University",
	"AdventHealth University",
	"American Institute of Beauty",
	"Atlantic Technical College",
	"Atlantis University",
	"Ave Maria University",
	"Aveda Institute-South Florida",
	"Aveda Institute-Tallahassee",
	"Aviation Institute of Maintenance-Orlando",
	"Barry University",
	"Bene's Career Academy",
	"Bethune-Cookman University",
	"Big Bend Technical College",
	"Broward College",
	"Charlotte Technical College",
	"Chipola College",
	"City College at Gainesville",
	"College of Central Florida",
	"Concorde Career Institute-Miramar",
	"Cortiva Institute-Maitland",
	"Daytona State College",
	"Eastern Florida State College",
	"Eckerd College",
	"Edward Waters College",
	"Embry-Riddle Aeronautical University at Daytona Beach",
	"Erwin Technical College",
	"Everglades University",
	"First Coast Technical College",
	"Flagler College",
	"Flagler Technical College",
	"Florida A&M University",
	"Florida Atlantic University",
	"Florida Career College at Tampa",
	"Florida College",
	"Florida Gateway College",
	"Florida Gulf Coast University",
	"Florida Institute of Recording Sound and Technology",
	"Florida Institute of Technology",
	"Florida International University",
	"Florida Memorial University",
	"Florida National University",
	"Florida Polytechnic University",
	"Florida SouthWestern State College",
	"Florida Southern College",
	"Florida State College at Jacksonville",
	"Florida State University",
	"Florida Technical College",
	"Fort Myers Technical College",
	"Fortis Institute at Port Saint Lucie",
	"Fred K. Marchman Technical College",
	"Full Sail University",
	"Gadsden Technical Institute",
	"George Stone Technical College",
	"Gulf Coast State College",
	"Gwinnett Institute",
	"HCI College",
	"HCI College at Fort Lauderdale",
	"Hillsborough Community College",
	"Immokalee Technical College",
	"Indian River State College",
	"Jacksonville University",
	"Johnson & Wales University-North Miami",
	"Keiser University Flagship",
	"Keiser University at Fort Myers",
	"Keiser University at Jacksonville",
	"Keiser University at Lakeland",
	"Keiser University at Melbourne",
	"Keiser University at Sarasota",
	"Keiser University at Tallahassee",
	"Keiser University at West Palm Beach",
	"Keiser University-Daytona",
	"Keiser University-Port St Lucie",
	"Lake Technical College",
	"Lake-Sumter State College",
	"Lindsey Hopkins Technical College",
	"Lively Technical College",
	"Loraines Academy & Spa",
	"Lorenzo Walker Technical College",
	"Lynn University",
	"Marion Technical College",
	"Meridian College",
	"Miami Dade College",
	"Miami International University of Art and Design",
	"New College of Florida",
	"North Florida College",
	"Northwest Florida State College",
	"Nouvelle Institute",
	"Nova Southeastern University",
	"Okaloosa Technical College",
	"Orange Technical College Mid Florida Campus",
	"Orange Technical College Orlando Campus",
	"Orange Technical College Westside Campus",
	"Orange Technical College Winter Park Campus",
	"Palm Beach Atlantic University",
	"Palm Beach State College",
	"Pasco-Hernando State College",
	"Paul Mitchell the School-Jacksonville",
	"Pensacola State College",
	"Pinellas Technical College-St. Petersburg",
	"Polk State College",
	"Praxis Institute",
	"Radford M Locklin Technical College",
	"Rasmussen College at Fort Myers",
	"Ridge Technical College",
	"Riveroak Technical College",
	"Rollins College",
	"Saint Leo University",
	"Santa Fe College",
	"Seminole State College of Florida",
	"Sheridan Technical College",
	"South Florida Bible College and Theological Seminary",
	"South Florida State College",
	"Southeastern College at West Palm Beach",
	"Southeastern University",
	"St. Johns River State College",
	"St. Petersburg College",
	"St. Thomas University",
	"State College of Florida, Manatee-Sarasota",
	"Stetson University",
	"Strayer University at Fort Lauderdale",
	"Suncoast Technical College",
	"Sunstate Academy-Jones Technical Institute",
	"Tallahassee Community College",
	"The College of the Florida Keys",
	"Traviss Technical College",
	"Trinity College of Florida",
	"Universal Technical Institute Orlando",
	"University of Central Florida",
	"University of Florida",
	"University of Fort Lauderdale",
	"University of Miami",
	"University of North Florida",
	"University of South Florida",
	"University of South Florida Sarasota-Manatee",
	"University of South Florida St. Petersburg",
	"University of Tampa",
	"University of West Florida",
	"Valencia College",
	"Warner University",
	"Webber International University",
	"William T. McFatter Technical College",
	"Withlacoochee Technical College",
	"Abraham Baldwin Agricultural College",
	"Agnes Scott College",
	"Albany State University",
	"Atlanta Metropolitan State College",
	"Augusta University",
	"Berry College",
	"Brenau University",
	"Clark Atlanta University",
	"Clayton State University",
	"College of Coastal Georgia",
	"Columbus State University",
	"Covenant College",
	"Dalton State College",
	"East Georgia State College",
	"Emmanuel College",
	"Emory University",
	"Fort Valley State University",
	"Georgia College & State University",
	"Georgia Gwinnett College",
	"Georgia Highlands College",
	"Georgia Institute of Technology",
	"Georgia Military College",
	"Georgia Southern University",
	"Georgia Southwestern State University",
	"Georgia State University",
	"Gordon State College",
	"Kennesaw State University",
	"LaGrange College",
	"Mercer University",
	"Middle Georgia State University",
	"Morehouse College",
	"Oglethorpe University",
	"Piedmont College",
	"Savannah State University",
	"Shorter University",
	"South Georgia State College",
	"University of Georgia",
	"University of North Georgia",
	"University of West Georgia",
	"Valdosta State University",
	"Wesleyan College",
	"Young Harris College",
	"University of Guam",
	"Brigham Young University-Hawaii",
	"Chaminade University of Honolulu",
	"Hawaii Pacific University",
	"Kapiolani Community College",
	"Leeward Community College",
	"University of Hawaii Maui College",
	"University of Hawaii at Hilo",
	"University of Hawaii at Manoa",
	"University of Hawaii-West Oahu",
	"Boise State University",
	"Brigham Young University-Idaho",
	"College of Idaho",
	"College of Southern Idaho",
	"Idaho State University",
	"Lewis-Clark State College",
	"North Idaho College",
	"Northwest Nazarene University",
	"University of Idaho",
	"Augustana College",
	"Aurora University",
	"Benedictine University",
	"Blackburn College",
	"Bradley University",
	"Chicago State University",
	"Columbia College Chicago",
	"Concordia University Chicago",
	"DePaul University",
	"Dominican University",
	"Eastern Illinois University",
	"Elmhurst University",
	"Eureka College",
	"Governors State University",
	"Greenville University",
	"Illinois College",
	"Illinois Institute of Technology",
	"Illinois State University",
	"Illinois Wesleyan University",
	"Kaskaskia College",
	"Knox College",
	"Lake Forest College",
	"Lake Land College",
	"Lewis University",
	"Loyola University Chicago",
	"McKendree University",
	"Midwestern University at Downers Grove",
	"Millikin University",
	"Monmouth College",
	"Moody Bible Institute",
	"North Central College",
	"North Park University",
	"Northeastern Illinois University",
	"Northern Illinois University",
	"Northwestern University",
	"Olivet Nazarene University",
	"Parkland College",
	"Principia College",
	"Quincy University",
	"Rockford University",
	"Saint Xavier University",
	"School of the Art Institute of Chicago",
	"Southeastern Illinois College",
	"Southern Illinois University Carbondale",
	"Southern Illinois University Edwardsville",
	"Southwestern Illinois College",
	"University of Chicago",
	"University of Illinois Springfield",
	"University of Illinois Urbana-Champaign",
	"University of Illinois at Chicago",
	"Western Illinois University",
	"Wheaton College",
	"Anderson University",
	"Ball State University",
	"Butler University",
	"DePauw University",
	"Earlham College",
	"Franklin College",
	"Goshen College",
	"Grace College and Theological Seminary",
	"Hanover College",
	"Indiana State University",
	"Indiana University Bloomington",
	"Indiana University East",
	"Indiana University Kokomo",
	"Indiana University Northwest",
	"Indiana University South Bend",
	"Indiana University Southeast",
	"Indiana University-Purdue University Indianapolis",
	"Ivy Tech Community College System",
	"Manchester University",
	"Marian University",
	"Oakland City University",
	"Purdue University",
	"Purdue University - Purdue Polytechnic Anderson",
	"Purdue University - Purdue Polytechnic Columbus",
	"Purdue University - Purdue Polytechnic Indianapolis",
	"Purdue University - Purdue Polytechnic Kokomo",
	"Purdue University - Purdue Polytechnic Lafayette",
	"Purdue University - Purdue Polytechnic New Albany",
	"Purdue University - Purdue Polytechnic Richmond",
	"Purdue University - Purdue Polytechnic South Bend",
	"Purdue University - Purdue Polytechnic Vincennes",
	"Purdue University Fort Wayne",
	"Purdue University Northwest",
	"Rose-Hulman Institute of Technology",
	"Saint Mary's College",
	"Taylor University",
	"Trine University",
	"University of Evansville",
	"University of Indianapolis",
	"University of Notre Dame",
	"University of Southern Indiana",
	"Valparaiso University",
	"Vincennes University",
	"Wabash College",
	"Buena Vista University",
	"Central College",
	"Clarke University",
	"Coe College",
	"Cornell College",
	"Dordt University",
	"Drake University",
	"Eastern Iowa Community College District",
	"Ellsworth Community College",
	"Graceland University",
	"Grand View University",
	"Grinnell College",
	"Hawkeye Community College",
	"Iowa State University",
	"Iowa Wesleyan University",
	"Loras College",
	"Luther College",
	"Marshalltown Community College",
	"Morningside College",
	"Northwestern College",
	"Saint Ambrose University",
	"Simpson College",
	"University of Dubuque",
	"University of Iowa",
	"University of Northern Iowa",
	"Upper Iowa University",
	"Wartburg College",
	"William Penn University",
	"Allen County Community College",
	"Baker University",
	"Benedictine College",
	"Bethany College (Kan.)",
	"Bethel College",
	"Butler Community College",
	"Central Christian College",
	"Dodge City Community College",
	"Emporia State University",
	"Flint Hills Technical College",
	"Fort Hays State University",
	"Haskell Indian Nations University",
	"Hesston College",
	"Hutchinson Community College",
	"Johnson County Community College",
	"Kansas State University",
	"Kansas Wesleyan University",
	"Labette Community College",
	"Newman University",
	"Pittsburg State University",
	"Southwestern College",
	"Sterling College",
	"University of Kansas",
	"University of Saint Mary",
	"Washburn University",
	"Wichita State University",
	"Alice Lloyd College",
	"Asbury Theological Seminary",
	"Asbury University",
	"Ashland Community and Technical College",
	"Beckfield College",
	"Bellarmine University",
	"Berea College",
	"Big Sandy Community and Technical College",
	"Bluegrass Community and Technical College",
	"Brescia University",
	"Campbellsville University",
	"Centre College",
	"Clear Creek Baptist Bible College",
	"Eastern Kentucky University",
	"Elizabethtown Community and Technical College",
	"Frontier Nursing University",
	"Galen College of Nursing-ARH",
	"Galen College of Nursing-Louisville",
	"Gateway Community and Technical College",
	"Georgetown College",
	"Hazard Community and Technical College",
	"Henderson Community College",
	"Hopkinsville Community College",
	"Jefferson Community and Technical College",
	"Kentucky Christian University",
	"Kentucky State University",
	"Kentucky Wesleyan College",
	"Lexington Healing Arts Academy",
	"Lexington Theological Seminary",
	"Lindsey Wilson College",
	"Madisonville Community College",
	"Maysville Community and Technical College",
	"MedQuest College",
	"Midway University",
	"Morehead State University",
	"Murray State University",
	"Northern Kentucky University",
	"Owensboro Community and Technical College",
	"Paul Mitchell the School-Lexington",
	"Simmons College of Kentucky",
	"Somerset Community College",
	"Southcentral Kentucky Community and Technical College",
	"Southeast Kentucky Community and Technical College",
	"Spalding University",
	"Sullivan University",
	"The Southern Baptist Theological Seminary",
	"Thomas More University",
	"Transylvania University",
	"Union College",
	"University of Kentucky",
	"University of Louisville",
	"University of Pikeville",
	"University of the Cumberlands",
	"West Kentucky Community and Technical College",
	"Western Kentucky University",
	"Baton Rouge Community College",
	"Bossier Parish Community College",
	"Centenary College of Louisiana",
	"Central Louisiana Technical Community College",
	"Delgado Community College",
	"Dillard University",
	"Fletcher Technical Community College",
	"Franciscan Missionaries of Our Lady University",
	"Grambling State University",
	"Louisiana College",
	"Louisiana Delta Community College",
	"Louisiana State University",
	"Louisiana State University Alexandria",
	"Louisiana State University Eunice",
	"Louisiana State University Health Sciences Center, New Orleans",
	"Louisiana State University Health Sciences Center, Shreveport",
	"Louisiana State University Shreveport",
	"Louisiana Tech University",
	"Loyola University New Orleans",
	"McNeese State University",
	"New Orleans Baptist Theological Seminary",
	"Nicholls State University",
	"Northshore Technical Community College",
	"Northwest Louisiana Technical College",
	"Northwestern State University of Louisiana",
	"Nunez Community College",
	"River Parishes Community College",
	"SOWELA Technical Community College",
	"Saint Joseph Seminary College",
	"South Louisiana Community College",
	"Southeastern Louisiana University",
	"Southern University Law Center",
	"Southern University and A&M College",
	"Southern University at New Orleans",
	"Southern University at Shreveport",
	"Tulane University of Louisiana",
	"University of Holy Cross",
	"University of Louisiana Monroe",
	"University of Louisiana at Lafayette",
	"University of New Orleans",
	"Xavier University of Louisiana",
	"Bates College",
	"Bowdoin College",
	"Colby College",
	"Husson University",
	"Maine Maritime Academy",
	"Saint Joseph's College of Maine",
	"Thomas College",
	"University of Maine",
	"University of Maine Farmington",
	"University of Maine at Augusta",
	"University of Maine at Fort Kent",
	"University of Maine at Machias",
	"University of Maine at Presque Isle",
	"University of New England",
	"University of Southern Maine",
	"College of the Marshall Islands",
	"Bowie State University",
	"Coppin State University",
	"Frostburg State University",
	"Goucher College",
	"Hood College",
	"Johns Hopkins University",
	"Loyola University Maryland",
	"McDaniel College",
	"Morgan State University",
	"Mount St. Mary's University",
	"Notre Dame of Maryland University",
	"Salisbury University",
	"St. Mary's College of Maryland",
	"Stevenson University",
	"Towson University",
	"United States Naval Academy",
	"University of Baltimore",
	"University of Maryland Eastern Shore",
	"University of Maryland, Baltimore",
	"University of Maryland, Baltimore County",
	"University of Maryland, College Park",
	"Washington College",
	"American International College",
	"Amherst College",
	"Anna Maria College",
	"Assumption College",
	"Babson College",
	"Bay Path University",
	"Becker College",
	"Bentley University",
	"Boston College",
	"Boston University",
	"Brandeis University",
	"Bridgewater State University",
	"Clark University",
	"College of Our Lady of the Elms",
	"College of the Holy Cross",
	"Curry College",
	"Dean College",
	"Eastern Nazarene College",
	"Emerson College",
	"Emmanuel College",
	"Endicott College",
	"Fitchburg State University",
	"Framingham State University",
	"Franklin W Olin College of Engineering",
	"Gordon College",
	"Hampshire College",
	"Harvard University",
	"Hebrew College",
	"Lasell University",
	"Lesley University",
	"Massachusetts College of Art and Design",
	"Massachusetts College of Liberal Arts",
	"Massachusetts College of Pharmacy and Health Sciences",
	"Massachusetts Institute of Technology",
	"Massachusetts Maritime Academy",
	"Merrimack College",
	"Mount Holyoke College",
	"Nichols College",
	"Northeastern University",
	"Pine Manor College",
	"Regis College",
	"Salem State University",
	"Simmons University",
	"Smith College",
	"Springfield College",
	"Stonehill College",
	"Suffolk University",
	"Tufts University",
	"University of Massachusetts Amherst",
	"University of Massachusetts Boston",
	"University of Massachusetts Dartmouth",
	"University of Massachusetts Lowell",
	"University of Massachusetts Medical School",
	"Wellesley College",
	"Wentworth Institute of Technology",
	"Western New England University",
	"Westfield State University",
	"Wheaton College",
	"Williams College",
	"Worcester Polytechnic Institute",
	"Worcester State University",
	"Adrian College",
	"Albion College",
	"Alma College",
	"Alpena Community College",
	"Andrews University",
	"Aquinas College",
	"Bay College",
	"Bay Mills Community College",
	"Calvin University",
	"Central Michigan University",
	"Cleary University",
	"Concordia University Ann Arbor",
	"Cornerstone University",
	"Davenport University",
	"Eastern Michigan University",
	"Ferris State University",
	"Finlandia University",
	"Glen Oaks Community College",
	"Grand Rapids Community College",
	"Grand Valley State University",
	"Great Lakes Christian College",
	"Henry Ford College",
	"Hillsdale College",
	"Hope College",
	"Jackson College",
	"Kalamazoo College",
	"Kettering University",
	"Kuyper College",
	"Lake Michigan College",
	"Lake Superior State University",
	"Lawrence Technological University",
	"Madonna University",
	"Michigan State University",
	"Michigan Technological University",
	"Mid Michigan College",
	"Mott Community College",
	"Northern Michigan University",
	"Northwestern Michigan College",
	"Northwood University",
	"Oakland University",
	"Olivet College",
	"Rochester University",
	"Saginaw Valley State University",
	"Schoolcraft College",
	"Siena Heights University",
	"Spring Arbor University",
	"University of Detroit Mercy",
	"University of Michigan",
	"University of Michigan-Dearborn",
	"University of Michigan-Flint",
	"Washtenaw Community College",
	"Wayne State University",
	"Western Michigan University",
	"Alexandria Technical & Community College",
	"Anoka Technical College",
	"Anoka-Ramsey Community College",
	"Augsburg University",
	"Bemidji State University",
	"Bethany Lutheran College",
	"Bethel University",
	"Carleton College",
	"Central Lakes College-Brainerd",
	"Central Lakes College-Staples",
	"Century College",
	"College of Saint Benedict and Saint John's University",
	"Concordia College at Moorhead",
	"Concordia University, St. Paul",
	"Crown College",
	"Dakota County Technical College",
	"Fond du Lac Tribal and Community College",
	"Gustavus Adolphus College",
	"Hamline University",
	"Hennepin Technical College",
	"Hibbing Community College",
	"Inver Hills Community College",
	"Itasca Community College",
	"Lake Superior College",
	"Macalester College",
	"Martin Luther College",
	"Mesabi Range College",
	"Mesabi Range College",
	"Metropolitan State University",
	"Minneapolis Community and Technical College",
	"Minnesota State College Southeast",
	"Minnesota State Community and Technical College",
	"Minnesota State University Moorhead",
	"Minnesota State University, Mankato",
	"Minnesota West Community and Technical College",
	"Normandale Community College",
	"North Central University",
	"North Hennepin Community College",
	"Northland Community and Technical College",
	"Northwest Technical College",
	"Pine Technical & Community College",
	"Rainy River Community College",
	"Ridgewater College",
	"Riverland Community College",
	"Rochester Community and Technical College",
	"Saint Mary's University of Minnesota",
	"South Central College",
	"Southwest Minnesota State University",
	"St. Catherine University",
	"St. Cloud State University",
	"St. Cloud Technical and Community College",
	"St. Olaf College",
	"St. Paul College",
	"The College of Saint Scholastica",
	"University of Minnesota Crookston",
	"University of Minnesota Duluth",
	"University of Minnesota Morris",
	"University of Minnesota Rochester",
	"University of Minnesota Twin Cities",
	"University of Northwestern, St. Paul",
	"University of St. Thomas",
	"Vermilion Community College",
	"Winona State University",
	"Alcorn State University",
	"Belhaven University",
	"Delta State University",
	"Jackson State University",
	"Millsaps College",
	"Mississippi College",
	"Mississippi Delta Community College",
	"Mississippi State University",
	"Mississippi University for Women",
	"Mississippi Valley State University",
	"Northeast Mississippi Community College",
	"Rust College",
	"University of Mississippi",
	"University of Mississippi Medical Center",
	"University of Southern Mississippi",
	"Central Methodist University",
	"College of the Ozarks",
	"Crowder College",
	"Drury University",
	"Evangel University",
	"Fontbonne University",
	"Graceland University at Independence",
	"Harris-Stowe State University",
	"Kansas City Art Institute",
	"Lincoln University of Missouri",
	"Lindenwood University",
	"Maryville University Saint Louis",
	"Missouri Baptist University",
	"Missouri Southern State University",
	"Missouri State University",
	"Missouri University of Science and Technology",
	"Missouri Western State University",
	"Northwest Missouri State University",
	"Ozarks Technical Community College",
	"Rockhurst University",
	"Saint Louis University",
	"Southeast Missouri State University",
	"Southwest Baptist University",
	"St. Louis College of Pharmacy",
	"St. Louis Community College",
	"State Fair Community College",
	"Stephens College",
	"Truman State University",
	"University of Central Missouri",
	"University of Missouri",
	"University of Missouri-Kansas City",
	"University of Missouri-St. Louis",
	"Washington University in St. Louis",
	"Webster University",
	"Westminster College",
	"William Jewell College",
	"William Woods University",
	"Carroll College",
	"Dawson Community College",
	"Flathead Valley Community College",
	"Great Falls College Montana State University",
	"Helena College",
	"Little Big Horn College",
	"Miles Community College",
	"Montana Bible College",
	"Montana State University",
	"Montana State University Billings",
	"Montana State University Northern",
	"Montana Technological University",
	"Pima Medical Institute-Dillon",
	"Rocky Mountain College",
	"Salish Kootenai College",
	"Stone Child College",
	"University of Montana",
	"University of Montana Western",
	"Chadron State College",
	"Concordia University, Nebraska",
	"Creighton University",
	"Doane University",
	"Hastings College",
	"Midland University",
	"Nebraska Wesleyan University",
	"Peru State College",
	"Southeast Community College",
	"University of Nebraska Medical Center",
	"University of Nebraska at Kearney",
	"University of Nebraska at Omaha",
	"University of Nebraska-Lincoln",
	"Wayne State College",
	"College of Southern Nevada",
	"Great Basin College",
	"Nevada State College",
	"Truckee Meadows Community College",
	"University of Nevada, Las Vegas",
	"University of Nevada, Reno",
	"Western Nevada College",
	"Antioch University-New England",
	"Colby-Sawyer College",
	"Dartmouth College",
	"Franklin Pierce University",
	"Granite State College",
	"Great Bay Community College",
	"Keene State College",
	"Lakes Region Community College",
	"Magdalen College",
	"NHTI-Concord's Community College",
	"Nashua Community College",
	"New England College",
	"Plymouth State University",
	"River Valley Community College",
	"Rivier University",
	"Saint Anselm College",
	"Southern New Hampshire University",
	"St. Joseph School of Nursing",
	"Thomas More College of Liberal Arts",
	"University of New Hampshire",
	"Upper Valley Educators Institute",
	"White Mountains Community College",
	"Berkeley College New Jersey campuses",
	"Bloomfield College",
	"Caldwell University",
	"Centenary University",
	"Drew University",
	"Fairleigh Dickinson University",
	"Fairleigh Dickinson University Florham",
	"Felician University",
	"Georgian Court University",
	"Kean University",
	"Monmouth University",
	"Montclair State University",
	"New Jersey City University",
	"New Jersey Institute of Technology",
	"Princeton University",
	"Ramapo College of New Jersey",
	"Rider University",
	"Rowan University",
	"Rutgers University",
	"Rutgers University-Camden",
	"Rutgers University-Newark",
	"Saint Elizabeth University",
	"Saint Peter's University",
	"Seton Hall University",
	"Stevens Institute of Technology",
	"Stockton University",
	"The College of New Jersey",
	"Thomas Edison State University",
	"William Paterson University",
	"Eastern New Mexico University",
	"Institute of American Indian Arts",
	"Navajo Technical University",
	"New Mexico Highlands University",
	"New Mexico Institute of Mining and Technology",
	"New Mexico Military Institute",
	"New Mexico State University",
	"Northern New Mexico College",
	"San Juan College",
	"Santa Fe Community College",
	"University of New Mexico",
	"Western New Mexico University",
	"ASA College",
	"Adelphi University",
	"Adirondack Community College",
	"Albany College of Pharmacy and Health Sciences",
	"Albany Medical College",
	"Albert Einstein College of Medicine",
	"Alfred University",
	"Bank Street College of Education",
	"Bard College",
	"Barnard College",
	"Berkeley College New York campuses",
	"Boricua College",
	"Bryant & Stratton College",
	"Bryant & Stratton College-Albany",
	"Bryant & Stratton College-Amherst",
	"Bryant & Stratton College-Buffalo",
	"Bryant & Stratton College-Greece",
	"Bryant & Stratton College-Henrietta",
	"Bryant & Stratton College-Southtowns",
	"Bryant & Stratton College-Syracuse North",
	"CUNY Baruch College",
	"CUNY Borough of Manhattan Community College",
	"CUNY Bronx Community College",
	"CUNY Brooklyn College",
	"CUNY City College of New York",
	"CUNY College of Staten Island",
	"CUNY Guttman Community College",
	"CUNY Hostos Community College",
	"CUNY Hunter College",
	"CUNY John Jay College of Criminal Justice",
	"CUNY Kingsborough Community College",
	"CUNY LaGuardia Community College",
	"CUNY Lehman College",
	"CUNY Medgar Evers College",
	"CUNY New York City College of Technology",
	"CUNY Queens College",
	"CUNY Queensborough Community College",
	"CUNY School of Law",
	"CUNY York College",
	"Canisius College",
	"Cayuga County Community College",
	"Cazenovia College",
	"Clarkson University",
	"Clarkson University Capital Region Campus",
	"Clinton Community College",
	"Colgate University",
	"College of Mount Saint Vincent",
	"Columbia University",
	"Columbia-Greene Community College",
	"Concordia College New York",
	"Cornell University",
	"Culinary Institute of America",
	"D'Youville College",
	"Daemen College",
	"Davis College",
	"DeVry College of New York",
	"Dominican College",
	"Dutchess Community College",
	"Elim Bible Institute and College",
	"Elmira Business Institute",
	"Elmira College",
	"Elyon College",
	"Erie Community College",
	"Excelsior College",
	"Farmingdale State College",
	"Fashion Institute of Technology",
	"Finger Lakes Community College",
	"Finger Lakes Health College of Nursing & Health Sciences",
	"Five Towns College",
	"Fordham University",
	"Fulton-Montgomery Community College",
	"Genesee Community College",
	"Glasgow Caledonian New York College",
	"Hamilton College",
	"Hartwick College",
	"Hebrew Union College-Jewish Institute of Religion",
	"Helene Fuld College of Nursing",
	"Herkimer County Community College",
	"Hilbert College",
	"Hobart William Smith Colleges",
	"Hofstra University",
	"Houghton College",
	"Hudson Valley Community College",
	"Icahn School of Medicine at Mount Sinai",
	"Iona College",
	"Ithaca College",
	"Jamestown Business College",
	"Jamestown Community College",
	"Jefferson Community College",
	"Keuka College",
	"Le Moyne College",
	"Long Island Business Institute",
	"Long Island University",
	"Manhattan College",
	"Manhattanville College",
	"Maria College of Albany",
	"Marist College",
	"Marymount Manhattan College",
	"Medaille College",
	"Mercy College",
	"Metropolitan College of New York",
	"Mildred Elley School-Albany Campus",
	"Mildred Elley-New York Campus",
	"Mohawk Valley Community College",
	"Molloy College",
	"Monroe College",
	"Monroe Community College",
	"Mount Saint Mary College",
	"Nassau Community College",
	"Nazareth College",
	"New York Automotive and Diesel Institute",
	"New York Chiropractic College",
	"New York College of Health Professions",
	"New York College of Podiatric Medicine",
	"New York College of Traditional Chinese Medicine",
	"New York Institute of Technology",
	"New York Law School",
	"New York Medical College",
	"New York School of Interior Design",
	"New York University",
	"Niagara County Community College",
	"Niagara University",
	"Northeastern Seminary",
	"Nyack College",
	"Onondaga Community College",
	"Orange County Community College",
	"Pace University",
	"Pacific College of Oriental Medicine",
	"Paul Smiths College",
	"Plaza College",
	"Pratt Institute",
	"Rensselaer Polytechnic Institute",
	"Roberts Wesleyan College",
	"Rochester Institute of Technology",
	"Rockefeller University",
	"Rockland Community College",
	"Russell Sage College",
	"SUNY Albany",
	"SUNY Alfred State College of Technology",
	"SUNY Binghamton",
	"SUNY Brockport",
	"SUNY Broome Community College",
	"SUNY Buffalo State",
	"SUNY Canton",
	"SUNY Cobleskill",
	"SUNY College at Potsdam",
	"SUNY College of Environmental Science and Forestry",
	"SUNY College of Optometry",
	"SUNY Corning Community College",
	"SUNY Cortland",
	"SUNY Delhi",
	"SUNY Downstate Health Sciences University",
	"SUNY Empire State College",
	"SUNY Geneseo",
	"SUNY Maritime College",
	"SUNY Morrisville",
	"SUNY New Paltz",
	"SUNY Old Westbury",
	"SUNY Oneonta",
	"SUNY Oswego",
	"SUNY Plattsburgh",
	"SUNY Polytechnic Institute",
	"SUNY Purchase College",
	"SUNY University at Buffalo",
	"SUNY Westchester Community College",
	"SUNY at Fredonia",
	"Saint Elizabeth College of Nursing",
	"Sarah Lawrence College",
	"Schenectady County Community College",
	"Siena College",
	"Skidmore College",
	"Sotheby's Institute of Art",
	"St. Bonaventure University",
	"St. Francis College",
	"St. John Fisher College",
	"St. John's University",
	"St. Joseph's College Long Island",
	"St. Joseph's College New York",
	"St. Joseph's College of Nursing",
	"St. Lawrence University",
	"St. Thomas Aquinas College",
	"Stony Brook University",
	"Suffolk County Community College",
	"Sullivan County Community College",
	"Swedish Institute a College of Health Sciences",
	"Syracuse University",
	"The College of Saint Rose",
	"The College of Westchester",
	"The Graduate Center, CUNY",
	"The King's College",
	"The New School",
	"Tompkins Cortland Community College",
	"Touro College",
	"Trocaire College",
	"Ulster County Community College",
	"Union College",
	"United States Merchant Marine Academy",
	"United States Military Academy West Point",
	"University of Rochester",
	"Upstate Medical University",
	"Utica College",
	"Vassar College",
	"Vaughn College of Aeronautics and Technology",
	"Villa Maria College",
	"Wagner College",
	"Webb Institute",
	"Weill Cornell Medical College",
	"Wells College",
	"Word of Life Bible Institute",
	"Yeshiva University",
	"Appalachian State University",
	"Barton College",
	"Belmont Abbey College",
	"Brevard College",
	"Campbell University",
	"Carolinas College of Health Sciences",
	"Catawba College",
	"Chowan University",
	"Davidson College",
	"Duke University",
	"Durham Technical Community College",
	"East Carolina University",
	"Elizabeth City State University",
	"Elon University",
	"Fayetteville State University",
	"Gardner-Webb University",
	"Greensboro College",
	"Guilford College",
	"High Point University",
	"Johnson & Wales University-Charlotte",
	"Johnson C Smith University",
	"Lees-McRae College",
	"Lenoir-Rhyne University",
	"Livingstone College",
	"Mars Hill University",
	"Meredith College",
	"Methodist University",
	"Montreat College",
	"North Carolina A&T State University",
	"North Carolina Central University",
	"North Carolina State University",
	"North Carolina Wesleyan College",
	"Pfeiffer University",
	"Queens University of Charlotte",
	"Saint Augustine's University",
	"Salem College",
	"Shaw University",
	"University of Mount Olive",
	"University of North Carolina Asheville",
	"University of North Carolina School of the Arts",
	"University of North Carolina Wilmington",
	"University of North Carolina at Chapel Hill",
	"University of North Carolina at Charlotte",
	"University of North Carolina at Greensboro",
	"University of North Carolina at Pembroke",
	"Wake Forest University",
	"Wake Technical Community College",
	"Warren Wilson College",
	"Western Carolina University",
	"William Peace University",
	"Wingate University",
	"Winston-Salem State University",
	"Bismarck State College",
	"Dakota College at Bottineau",
	"Dickinson State University",
	"Lake Region State College",
	"Mayville State University",
	"Minot State University",
	"North Dakota State College of Science",
	"North Dakota State University",
	"Nueta Hidatsa Sahnish College",
	"Sitting Bull College",
	"University of Mary",
	"University of North Dakota",
	"Valley City State University",
	"Williston State College",
	"Northern Marianas College",
	"Air Force Institute of Technology-Graduate School of Engineering & Management",
	"Ashland University",
	"Baldwin Wallace University",
	"Bluffton University",
	"Bowling Green State University",
	"Bowling Green State University Firelands",
	"Capital University",
	"Case Western Reserve University",
	"Cedarville University",
	"Central State University",
	"Clark State Community College",
	"Cleveland State University",
	"Columbus College of Art and Design",
	"Cuyahoga Community College District",
	"Defiance College",
	"Denison University",
	"Franciscan University of Steubenville",
	"Heidelberg University",
	"Hiram College",
	"John Carroll University",
	"Kent State University",
	"Kent State University Geauga Campus",
	"Kent State University at Ashtabula",
	"Kent State University at East Liverpool",
	"Kent State University at Salem",
	"Kent State University at Stark",
	"Kent State University at Trumbull",
	"Kent State University at Tuscarawas",
	"Kenyon College",
	"Lake Erie College",
	"Lorain County Community College",
	"Lourdes University",
	"Malone University",
	"Marietta College",
	"Miami University (Ohio)",
	"Mount Saint Joseph University",
	"Muskingum University",
	"North Central State College",
	"Northeast Ohio Medical University",
	"Notre Dame College",
	"Oberlin College",
	"Ohio Dominican University",
	"Ohio Northern University",
	"Ohio State University",
	"Ohio University",
	"Ohio University-Chillicothe",
	"Ohio University-Eastern",
	"Ohio University-Lancaster",
	"Ohio University-Southern",
	"Ohio University-Zanesville",
	"Ohio Wesleyan University",
	"Otterbein University",
	"Shawnee State University",
	"Sinclair Community College",
	"Terra State Community College",
	"The College of Wooster",
	"The University of Findlay",
	"Tiffin University",
	"University of Akron",
	"University of Cincinnati",
	"University of Dayton",
	"University of Mount Union",
	"University of Toledo",
	"Ursuline College",
	"Walsh University",
	"Wilmington College",
	"Wittenberg University",
	"Wright State University",
	"Wright State University-Lake Campus",
	"Xavier University",
	"Youngstown State University",
	"Cameron University",
	"East Central University",
	"Langston University",
	"Northeastern State University",
	"Northern Oklahoma College",
	"Northwestern Oklahoma State University",
	"Oklahoma Baptist University",
	"Oklahoma Christian University",
	"Oklahoma City University",
	"Oklahoma Panhandle State University",
	"Oklahoma State University",
	"Oklahoma State University Center for Health Sciences",
	"Oklahoma State University Institute of Technology",
	"Oklahoma State University-Oklahoma City",
	"Oral Roberts University",
	"Rogers State University",
	"Rose State College",
	"Southeastern Oklahoma State University",
	"Southern Nazarene University",
	"Southwestern Oklahoma State University",
	"University of Central Oklahoma",
	"University of Oklahoma",
	"University of Science and Arts of Oklahoma",
	"University of Tulsa",
	"Eastern Oregon University",
	"George Fox University",
	"Lane Community College",
	"Lewis & Clark College",
	"Linfield University",
	"Linfield University-School of Nursing",
	"Oregon Health & Science University",
	"Oregon Institute of Technology",
	"Oregon State University",
	"Oregon State University-Cascades",
	"Pacific University",
	"Portland State University",
	"Reed College",
	"Southern Oregon University",
	"University of Oregon",
	"University of Portland",
	"Western Oregon University",
	"Willamette University",
	"Albright College",
	"Allegheny College",
	"Alvernia University",
	"Arcadia University",
	"Bloomsburg University of Pennsylvania",
	"Bryn Athyn College",
	"Bryn Mawr College",
	"Bucknell University",
	"Cabrini University",
	"Cairn University",
	"California University of Pennsylvania",
	"Carnegie Mellon University",
	"Cedar Crest College",
	"Chatham University",
	"Chestnut Hill College",
	"Cheyney University of Pennsylvania",
	"Clarion University of Pennsylvania",
	"Clarks Summit University",
	"Community College of Allegheny County",
	"DeSales University",
	"Delaware Valley University",
	"Dickinson College",
	"Drexel University",
	"Duquesne University",
	"East Stroudsburg University",
	"Eastern University",
	"Edinboro University",
	"Elizabethtown College",
	"Franklin and Marshall College",
	"Gannon University",
	"Geneva College",
	"Gettysburg College",
	"Grove City College",
	"Gwynedd Mercy University",
	"Haverford College",
	"Holy Family University",
	"Immaculata University",
	"Indiana University of Pennsylvania",
	"Juniata College",
	"Keystone College",
	"King's College",
	"Kutztown University",
	"La Roche University",
	"La Salle University",
	"Lafayette College",
	"Lancaster Bible College",
	"Lebanon Valley College",
	"Lehigh University",
	"Lincoln University",
	"Lock Haven University",
	"Lycoming College",
	"Mansfield University of Pennsylvania",
	"Marywood University",
	"Mercyhurst University",
	"Messiah University",
	"Millersville University of Pennsylvania",
	"Misericordia University",
	"Moravian College",
	"Mount Aloysius College",
	"Muhlenberg College",
	"Neumann University",
	"Penn State University",
	"Pennsylvania College of Technology",
	"Point Park University",
	"Robert Morris University",
	"Rosemont College",
	"Saint Francis University",
	"Saint Joseph's University",
	"Saint Vincent College",
	"Seton Hill University",
	"Shippensburg University of Pennsylvania",
	"Slippery Rock University of Pennsylvania",
	"Susquehanna University",
	"Swarthmore College",
	"Temple University",
	"Thiel College",
	"Thomas Jefferson University",
	"University of Pennsylvania",
	"University of Pittsburgh",
	"University of Pittsburgh Johnstown",
	"University of Pittsburgh at Bradford",
	"University of Pittsburgh at Greensburg",
	"University of Scranton",
	"University of Valley Forge",
	"University of the Sciences",
	"Ursinus College",
	"Villanova University",
	"Washington & Jefferson College",
	"Waynesburg University",
	"West Chester University",
	"Westminster College",
	"Widener University",
	"Wilkes University",
	"Wilson College",
	"York College of Pennsylvania",
	"Colegio Universitario de San Juan",
	"Conservatory of Music of Puerto Rico",
	"Escuela de Artes Plasticas y Diseno de Puerto Rico",
	"University of Puerto Rico",
	"Brown University",
	"Bryant University",
	"Johnson & Wales University",
	"Providence College",
	"Rhode Island College",
	"Rhode Island School of Design",
	"Roger Williams University",
	"Salve Regina University",
	"University of Rhode Island",
	"Anderson University",
	"Benedict College",
	"Bob Jones University",
	"Charleston Southern University",
	"Claflin University",
	"Clemson University",
	"Coastal Carolina University",
	"Coker University",
	"College of Charleston",
	"Converse College",
	"Erskine College",
	"Francis Marion University",
	"Furman University",
	"Greenville Technical College",
	"Lander University",
	"Limestone College",
	"Medical University of South Carolina",
	"Newberry College",
	"North Greenville University",
	"Presbyterian College",
	"South Carolina State University",
	"Southern Wesleyan University",
	"The Citadel",
	"Tri-County Technical College",
	"University of South Carolina",
	"University of South Carolina Aiken",
	"University of South Carolina Beaufort",
	"University of South Carolina Upstate",
	"Winthrop University",
	"Wofford College",
	"Augustana University",
	"Black Hills State University",
	"Dakota State University",
	"Mount Marty College",
	"Northern State University",
	"Oglala Lakota College",
	"Sinte Gleska University",
	"South Dakota School of Mines and Technology",
	"South Dakota State University",
	"University of Sioux Falls",
	"University of South Dakota",
	"Austin Peay State University",
	"Belmont University",
	"Bethel University",
	"Carson-Newman University",
	"Chattanooga State Community College",
	"Christian Brothers University",
	"Cleveland State Community College",
	"Columbia State Community College",
	"Cumberland University",
	"Dyersburg State Community College",
	"East Tennessee State University",
	"Jackson State Community College",
	"King University",
	"Lane College",
	"LeMoyne-Owen College",
	"Lee University",
	"Lincoln Memorial University",
	"Lipscomb University",
	"Maryville College",
	"Middle Tennessee State University",
	"Milligan University",
	"Motlow State Community College",
	"Nashville State Community College",
	"Northeast State Community College",
	"Pellissippi State Community College",
	"Rhodes College",
	"Roane State Community College",
	"Southern Adventist University",
	"Southwest Tennessee Community College",
	"Tennessee College of Applied Technology",
	"Tennessee State University",
	"Tennessee Technological University",
	"The University of the South",
	"Trevecca Nazarene University",
	"Tusculum University",
	"Union University",
	"University of Memphis",
	"University of Tennessee Health Science Center",
	"University of Tennessee at Chattanooga",
	"University of Tennessee at Martin",
	"University of Tennessee, Knoxville",
	"Vanderbilt University",
	"Volunteer State Community College",
	"Walters State Community College",
	"Abilene Christian University",
	"Angelo State University",
	"Austin College",
	"Austin Community College District",
	"Baylor University",
	"Blinn College",
	"Brazosport College",
	"Collin College McKinney",
	"Concordia University Texas",
	"Dallas Baptist University",
	"East Texas Baptist University",
	"Galveston College",
	"Grayson College",
	"Hardin-Simmons University",
	"Hill College",
	"Houston Baptist University",
	"Howard Payne University",
	"Lamar University",
	"Laredo College",
	"LeTourneau University",
	"Lubbock Christian University",
	"McLennan Community College",
	"McMurry University",
	"Midland College",
	"Midwestern State University",
	"Odessa College",
	"Prairie View A&M University",
	"Rice University",
	"Saint Edward's University",
	"Sam Houston State University",
	"Schreiner University",
	"South Plains College",
	"South Texas College",
	"Southern Methodist University",
	"Southwestern University",
	"St. Mary's University",
	"Stephen F. Austin State University",
	"Sul Ross State University",
	"Tarleton State University",
	"Texarkana College",
	"Texas A&M University",
	"Texas Christian University",
	"Texas College",
	"Texas Lutheran University",
	"Texas Southern University",
	"Texas State University",
	"Texas Tech University",
	"Texas Tech University Health Sciences Center",
	"Texas Tech University Health Sciences Center El Paso",
	"Texas Wesleyan University",
	"Texas Woman’s University",
	"Trinity University",
	"Tyler Junior College",
	"University of Dallas",
	"University of Houston",
	"University of Mary Hardin at Baylor",
	"University of North Texas",
	"University of North Texas Health Science Center",
	"University of North Texas at Dallas",
	"University of St. Thomas",
	"University of Texas",
	"University of the Incarnate Word",
	"Wayland Baptist University",
	"West Texas A&M University",
	"Brigham Young University",
	"Dixie State University",
	"Salt Lake Community College",
	"Snow College",
	"Southern Utah University",
	"University of Utah",
	"Utah State University",
	"Utah Valley University",
	"Weber State University",
	"Westminster College",
	"Bennington College",
	"Castleton University",
	"Champlain College",
	"Community College of Vermont",
	"Goddard College",
	"Landmark College",
	"Middlebury College",
	"Northern Vermont University-Johnson",
	"Northern Vermont University-Lyndon",
	"Norwich University",
	"Saint Michael's College",
	"Sterling College",
	"University of Vermont",
	"Vermont College of Fine Arts",
	"Vermont Law School",
	"Vermont Technical College",
	"University of the Virgin Islands",
	"Averett University",
	"Bluefield College",
	"Bridgewater College",
	"Christopher Newport University",
	"Danville Community College",
	"Eastern Mennonite University",
	"Eastern Virginia Medical School",
	"Emory & Henry College",
	"Ferrum College",
	"George Mason University",
	"Hampden-Sydney College",
	"Hampton University",
	"Hollins University",
	"James Madison University",
	"Liberty University",
	"Longwood University",
	"Mary Baldwin University",
	"Marymount University",
	"Norfolk State University",
	"Old Dominion University",
	"Radford University",
	"Randolph College",
	"Randolph-Macon College",
	"Roanoke College",
	"Shenandoah University",
	"Southern Virginia University",
	"Sweet Briar College",
	"University of Lynchburg",
	"University of Mary Washington",
	"University of Richmond",
	"University of Virginia",
	"University of Virginia's College at Wise",
	"Virginia Commonwealth University",
	"Virginia Highlands Community College",
	"Virginia Military Institute",
	"Virginia State University",
	"Virginia Tech",
	"Virginia Union University",
	"Virginia Wesleyan University",
	"Washington and Lee University",
	"William & Mary",
	"American University",
	"Catholic University of America",
	"Gallaudet University",
	"George Washington University",
	"Georgetown University",
	"Howard University",
	"Trinity Washington University",
	"University of the District of Columbia",
	"Bellevue College",
	"Bellingham Technical College",
	"Cascadia College",
	"Central Washington University",
	"Centralia College",
	"Clark College",
	"Clover Park Technical College",
	"Columbia Basin College",
	"Eastern Washington University",
	"Edmonds College",
	"Everett Community College",
	"Evergreen State College",
	"Gonzaga University",
	"Grays Harbor College",
	"Green River College",
	"Highline College",
	"Lake Washington Institute of Technology",
	"Lower Columbia College",
	"North Seattle College",
	"Northwest Indian College",
	"Olympic College",
	"Pacific Lutheran University",
	"Peninsula College",
	"Pierce College",
	"Renton Technical College",
	"Saint Martin's University",
	"Seattle Central College",
	"Seattle Pacific University",
	"Seattle University",
	"Skagit Valley College",
	"South Seattle College",
	"Spokane Community College",
	"Spokane Falls Community College",
	"Tacoma Community College",
	"University of Puget Sound",
	"University of Washington",
	"University of Washington Bothell",
	"University of Washington Tacoma",
	"Walla Walla Community College",
	"Washington State University",
	"Wenatchee Valley College",
	"Western Washington University",
	"Whatcom Community College",
	"Whitman College",
	"Whitworth University",
	"Yakima Valley College",
	"Alderson Broaddus University",
	"Bethany College (W.Va.)",
	"Bluefield State College",
	"Concord University",
	"Davis & Elkins College",
	"Fairmont State University",
	"Glenville State College",
	"Marshall University",
	"Ohio Valley University",
	"Potomac State College of West Virginia University",
	"Salem University",
	"Shepherd University",
	"University of Charleston",
	"West Liberty University",
	"West Virginia School of Osteopathic Medicine",
	"West Virginia State University",
	"West Virginia University",
	"West Virginia University Institute of Technology",
	"West Virginia University at Parkersburg",
	"West Virginia Wesleyan College",
	"Wheeling University",
	"Alverno College",
	"Beloit College",
	"Carroll University",
	"Carthage College",
	"Concordia University Wisconsin",
	"Edgewood College",
	"Lakeland University",
	"Lawrence University",
	"Madison Area Technical College",
	"Maranatha Baptist University",
	"Marian University",
	"Marquette University",
	"Milwaukee School of Engineering",
	"Mount Mary University",
	"Northland College",
	"Ripon College",
	"Saint Norbert College",
	"University of Wisconsin",
	"Viterbo University",
	"Wisconsin Lutheran College",
	"Casper College",
	"Eastern Wyoming College",
	"University of Wyoming",
	"Western Wyoming Community College",
];
