export const colleges = [
	"ASA College",
	"Abilene Christian University",
	"Abraham Baldwin Agricultural College",
	"Academy of Art University",
	"Adams State University",
	"Adelphi University",
	"Adirondack Community College",
	"Adrian College",
	"AdventHealth University",
	"Agnes Scott College",
	"Air Force Institute of Technology-Graduate School of Engineering & Management",
	"Alabama A&M University",
	"Alabama State University",
	"Albany College of Pharmacy and Health Sciences",
	"Albany Medical College",
	"Albany State University",
	"Albert Einstein College of Medicine",
	"Albertus Magnus College",
	"Albion College",
	"Albright College",
	"Alcorn State University",
	"Alderson Broaddus University",
	"Alexandria Technical & Community College",
	"Alfred University",
	"Alice Lloyd College",
	"Allegheny College",
	"Allen County Community College",
	"Alma College",
	"Alpena Community College",
	"Alvernia University",
	"Alverno College",
	"American Institute of Beauty",
	"American International College",
	"American Samoa Community College",
	"American University",
	"Amherst College",
	"Anderson University",
	"Anderson University",
	"Andrews University",
	"Angelo State University",
	"Anna Maria College",
	"Anoka Technical College",
	"Anoka-Ramsey Community College",
	"Antelope Valley College",
	"Antioch University-New England",
	"Appalachian State University",
	"Aquinas College",
	"Arapahoe Community College",
	"Arcadia University",
	"Arizona State University",
	"Arizona Western College",
	"Arkansas Northeastern College",
	"Arkansas State University",
	"Arkansas State University-Newport",
	"Arkansas Tech University",
	"Asbury Theological Seminary",
	"Asbury University",
	"Ashland Community and Technical College",
	"Ashland University",
	"Assumption College",
	"Athens State University",
	"Atlanta Metropolitan State College",
	"Atlantic Technical College",
	"Atlantis University",
	"Auburn University at Montgomery",
	"Auburn University",
	"Augsburg University",
	"Augusta University",
	"Augustana College",
	"Augustana University",
	"Aurora University",
	"Austin College",
	"Austin Community College District",
	"Austin Peay State University",
	"Ave Maria University",
	"Aveda Institute-South Florida",
	"Aveda Institute-Tallahassee",
	"Averett University",
	"Aviation Institute of Maintenance-Orlando",
	"Azusa Pacific University",
	"Babson College",
	"Baker University",
	"Bakersfield College",
	"Baldwin Wallace University",
	"Ball State University",
	"Bank Street College of Education",
	"Bard College",
	"Barnard College",
	"Barry University",
	"Barton College",
	"Bates College",
	"Baton Rouge Community College",
	"Bay College",
	"Bay Mills Community College",
	"Bay Path University",
	"Baylor University",
	"Becker College",
	"Beckfield College",
	"Belhaven University",
	"Bellarmine University",
	"Bellevue College",
	"Bellingham Technical College",
	"Belmont Abbey College",
	"Belmont University",
	"Beloit College",
	"Bemidji State University",
	"Bene's Career Academy",
	"Benedict College",
	"Benedictine College",
	"Benedictine University",
	"Bennington College",
	"Bentley University",
	"Berea College",
	"Berkeley College New Jersey campuses",
	"Berkeley College New York campuses",
	"Berry College",
	"Bethany College (Kan.)",
	"Bethany College (W.Va.)",
	"Bethany Lutheran College",
	"Bethel College",
	"Bethel University",
	"Bethel University",
	"Bethune-Cookman University",
	"Bevill State Community College",
	"Big Bend Technical College",
	"Big Sandy Community and Technical College",
	"Biola University",
	"Birmingham-Southern College",
	"Bismarck State College",
	"Black Hills State University",
	"Black River Technical College",
	"Blackburn College",
	"Blinn College",
	"Bloomfield College",
	"Bloomsburg University of Pennsylvania",
	"Bluefield College",
	"Bluefield State College",
	"Bluegrass Community and Technical College",
	"Bluffton University",
	"Bob Jones University",
	"Boise State University",
	"Boricua College",
	"Bossier Parish Community College",
	"Boston College",
	"Boston University",
	"Bowdoin College",
	"Bowie State University",
	"Bowling Green State University Firelands",
	"Bowling Green State University",
	"Bradley University",
	"Brandeis University",
	"Brazosport College",
	"Brenau University",
	"Brescia University",
	"Brevard College",
	"Bridgewater College",
	"Bridgewater State University",
	"Brigham Young University",
	"Brigham Young University-Hawaii",
	"Brigham Young University-Idaho",
	"Broward College",
	"Brown University",
	"Bryant & Stratton College",
	"Bryant & Stratton College-Albany",
	"Bryant & Stratton College-Amherst",
	"Bryant & Stratton College-Buffalo",
	"Bryant & Stratton College-Greece",
	"Bryant & Stratton College-Henrietta",
	"Bryant & Stratton College-Southtowns",
	"Bryant & Stratton College-Syracuse North",
	"Bryant University",
	"Bryn Athyn College",
	"Bryn Mawr College",
	"Bucknell University",
	"Buena Vista University",
	"Butler Community College",
	"Butler University",
	"CUNY Baruch College",
	"CUNY Borough of Manhattan Community College",
	"CUNY Bronx Community College",
	"CUNY Brooklyn College",
	"CUNY City College of New York",
	"CUNY College of Staten Island",
	"CUNY Guttman Community College",
	"CUNY Hostos Community College",
	"CUNY Hunter College",
	"CUNY John Jay College of Criminal Justice",
	"CUNY Kingsborough Community College",
	"CUNY LaGuardia Community College",
	"CUNY Lehman College",
	"CUNY Medgar Evers College",
	"CUNY New York City College of Technology",
	"CUNY Queens College",
	"CUNY Queensborough Community College",
	"CUNY School of Law",
	"CUNY York College",
	"Cabrini University",
	"Cairn University",
	"Caldwell University",
	"Calhoun Community College",
	"California Baptist University",
	"California Institute of Technology",
	"California Lutheran University",
	"California State Polytechnic University",
	"California State Polytechnic University",
	"California State University",
	"California University of Pennsylvania",
	"Calvin University",
	"Cameron University",
	"Campbell University",
	"Campbellsville University",
	"Canisius College",
	"Capital University",
	"Carleton College",
	"Carnegie Mellon University",
	"Carolinas College of Health Sciences",
	"Carroll College",
	"Carroll University",
	"Carson-Newman University",
	"Carthage College",
	"Cascadia College",
	"Case Western Reserve University",
	"Casper College",
	"Castleton University",
	"Catawba College",
	"Catholic University of America",
	"Cayuga County Community College",
	"Cazenovia College",
	"Cedar Crest College",
	"Cedarville University",
	"Centenary College of Louisiana",
	"Centenary University",
	"Central Alabama Community College",
	"Central Baptist College",
	"Central Christian College",
	"Central College",
	"Central Connecticut State University",
	"Central Lakes College-Brainerd",
	"Central Lakes College-Staples",
	"Central Louisiana Technical Community College",
	"Central Methodist University",
	"Central Michigan University",
	"Central State University",
	"Central Washington University",
	"Centralia College",
	"Centre College",
	"Century College",
	"Chadron State College",
	"Chaminade University of Honolulu",
	"Champlain College",
	"Chapman University",
	"Charleston Southern University",
	"Charlotte Technical College",
	"Chatham University",
	"Chattanooga State Community College",
	"Chestnut Hill College",
	"Cheyney University of Pennsylvania",
	"Chicago State University",
	"Chipola College",
	"Chowan University",
	"Christian Brothers University",
	"Christopher Newport University",
	"City College at Gainesville",
	"Claflin University",
	"Claremont McKenna College",
	"Clarion University of Pennsylvania",
	"Clark Atlanta University",
	"Clark College",
	"Clark State Community College",
	"Clark University",
	"Clarke University",
	"Clarks Summit University",
	"Clarkson University Capital Region Campus",
	"Clarkson University",
	"Clayton State University",
	"Clear Creek Baptist Bible College",
	"Cleary University",
	"Clemson University",
	"Cleveland State Community College",
	"Cleveland State University",
	"Clinton Community College",
	"Clover Park Technical College",
	"Coastal Carolina University",
	"Coe College",
	"Coker University",
	"Colby College",
	"Colby-Sawyer College",
	"Colegio Universitario de San Juan",
	"Colgate University",
	"College of Central Florida",
	"College of Charleston",
	"College of Coastal Georgia",
	"College of Idaho",
	"College of Mount Saint Vincent",
	"College of Our Lady of the Elms",
	"College of Saint Benedict and Saint John's University",
	"College of Southern Idaho",
	"College of Southern Nevada",
	"College of the Holy Cross",
	"College of the Marshall Islands",
	"College of the Ozarks",
	"Collin College McKinney",
	"Colorado Christian University",
	"Colorado College",
	"Colorado Mesa University",
	"Colorado Mountain College Glenwood Springs",
	"Colorado School of Mines",
	"Colorado State University",
	"Colorado State University-Pueblo",
	"Columbia Basin College",
	"Columbia College Chicago",
	"Columbia State Community College",
	"Columbia University",
	"Columbia-Greene Community College",
	"Columbus College of Art and Design",
	"Columbus State University",
	"Community College of Allegheny County",
	"Community College of Aurora",
	"Community College of Denver",
	"Community College of Vermont",
	"Concord University",
	"Concorde Career Institute-Miramar",
	"Concordia College New York",
	"Concordia College at Moorhead",
	"Concordia University Ann Arbor",
	"Concordia University Chicago",
	"Concordia University Irvine",
	"Concordia University Texas",
	"Concordia University Wisconsin",
	"Concordia University, Nebraska",
	"Concordia University, St. Paul",
	"Connecticut College",
	"Conservatory of Music of Puerto Rico",
	"Converse College",
	"Coppin State University",
	"Cornell College",
	"Cornell University",
	"Cornerstone University",
	"Cortiva Institute-Maitland",
	"Cossatot Community College of the University of Arkansas",
	"Covenant College",
	"Creighton University",
	"Crowder College",
	"Crown College",
	"Culinary Institute of America",
	"Cumberland University",
	"Curry College",
	"Cuyahoga Community College District",
	"Cypress College",
	"D'Youville College",
	"Daemen College",
	"Dakota College at Bottineau",
	"Dakota County Technical College",
	"Dakota State University",
	"Dallas Baptist University",
	"Dalton State College",
	"Danville Community College",
	"Dartmouth College",
	"Davenport University",
	"Davidson College",
	"Davis & Elkins College",
	"Davis College",
	"Dawson Community College",
	"Daytona State College",
	"DePaul University",
	"DePauw University",
	"DeSales University",
	"DeVry College of New York",
	"Dean College",
	"Defiance College",
	"Delaware State University",
	"Delaware Technical Community College Dover",
	"Delaware Technical Community College Georgetown",
	"Delaware Technical Community College Stanton",
	"Delaware Valley University",
	"Delgado Community College",
	"Delta State University",
	"Denison University",
	"Dickinson College",
	"Dickinson State University",
	"Dillard University",
	"Dine College",
	"Dixie State University",
	"Doane University",
	"Dodge City Community College",
	"Dominican College",
	"Dominican University of California",
	"Dominican University",
	"Dordt University",
	"Drake University",
	"Drew University",
	"Drexel University",
	"Drury University",
	"Duke University",
	"Duquesne University",
	"Durham Technical Community College",
	"Dutchess Community College",
	"Dyersburg State Community College",
	"Earlham College",
	"East Carolina University",
	"East Central University",
	"East Georgia State College",
	"East Stroudsburg University",
	"East Tennessee State University",
	"East Texas Baptist University",
	"Eastern Connecticut State University",
	"Eastern Florida State College",
	"Eastern Illinois University",
	"Eastern Iowa Community College District",
	"Eastern Kentucky University",
	"Eastern Mennonite University",
	"Eastern Michigan University",
	"Eastern Nazarene College",
	"Eastern New Mexico University",
	"Eastern Oregon University",
	"Eastern University",
	"Eastern Virginia Medical School",
	"Eastern Washington University",
	"Eastern Wyoming College",
	"Eckerd College",
	"Edgewood College",
	"Edinboro University",
	"Edmonds College",
	"Edward Waters College",
	"El Camino Community College",
	"Elim Bible Institute and College",
	"Elizabeth City State University",
	"Elizabethtown College",
	"Elizabethtown Community and Technical College",
	"Ellsworth Community College",
	"Elmhurst University",
	"Elmira Business Institute",
	"Elmira College",
	"Elon University",
	"Elyon College",
	"Embry-Riddle Aeronautical University at Daytona Beach",
	"Embry-Riddle Aeronautical University at Prescott",
	"Emerson College",
	"Emmanuel College",
	"Emmanuel College",
	"Emory & Henry College",
	"Emory University",
	"Emporia State University",
	"Endicott College",
	"Enterprise State Community College",
	"Erie Community College",
	"Erskine College",
	"Erwin Technical College",
	"Escuela de Artes Plasticas y Diseno de Puerto Rico",
	"Eureka College",
	"Evangel University",
	"Everett Community College",
	"Everglades University",
	"Evergreen State College",
	"Excelsior College",
	"Fairfield University",
	"Fairleigh Dickinson University Florham",
	"Fairleigh Dickinson University",
	"Fairmont State University",
	"Farmingdale State College",
	"Fashion Institute of Technology",
	"Fayetteville State University",
	"Feather River College",
	"Felician University",
	"Ferris State University",
	"Ferrum College",
	"Finger Lakes Community College",
	"Finger Lakes Health College of Nursing & Health Sciences",
	"Finlandia University",
	"First Coast Technical College",
	"Fitchburg State University",
	"Five Towns College",
	"Flagler College",
	"Flagler Technical College",
	"Flathead Valley Community College",
	"Fletcher Technical Community College",
	"Flint Hills Technical College",
	"Florida A&M University",
	"Florida Atlantic University",
	"Florida Career College at Tampa",
	"Florida College",
	"Florida Gateway College",
	"Florida Gulf Coast University",
	"Florida Institute of Recording Sound and Technology",
	"Florida Institute of Technology",
	"Florida International University",
	"Florida Memorial University",
	"Florida National University",
	"Florida Polytechnic University",
	"Florida SouthWestern State College",
	"Florida Southern College",
	"Florida State College at Jacksonville",
	"Florida State University",
	"Florida Technical College",
	"Fond du Lac Tribal and Community College",
	"Fontbonne University",
	"Foothill College",
	"Fordham University",
	"Fort Hays State University",
	"Fort Lewis College",
	"Fort Myers Technical College",
	"Fort Valley State University",
	"Fortis Institute at Port Saint Lucie",
	"Framingham State University",
	"Francis Marion University",
	"Franciscan Missionaries of Our Lady University",
	"Franciscan University of Steubenville",
	"Franklin College",
	"Franklin Pierce University",
	"Franklin W Olin College of Engineering",
	"Franklin and Marshall College",
	"Fred K. Marchman Technical College",
	"Fresno Pacific University",
	"Fresno State University",
	"Front Range Community College",
	"Frontier Nursing University",
	"Frostburg State University",
	"Full Sail University",
	"Fulton-Montgomery Community College",
	"Furman University",
	"Gadsden State Community College",
	"Gadsden Technical Institute",
	"Galen College of Nursing-ARH",
	"Galen College of Nursing-Louisville",
	"Gallaudet University",
	"Galveston College",
	"Gannon University",
	"Gardner-Webb University",
	"Gateway Community and Technical College",
	"Genesee Community College",
	"Geneva College",
	"George Fox University",
	"George Mason University",
	"George Stone Technical College",
	"George Washington University",
	"Georgetown College",
	"Georgetown University",
	"Georgia College & State University",
	"Georgia Gwinnett College",
	"Georgia Highlands College",
	"Georgia Institute of Technology",
	"Georgia Military College",
	"Georgia Southern University",
	"Georgia Southwestern State University",
	"Georgia State University",
	"Georgian Court University",
	"Gettysburg College",
	"Glasgow Caledonian New York College",
	"Glen Oaks Community College",
	"Glenville State College",
	"Goddard College",
	"Goldey-Beacom College",
	"Gonzaga University",
	"Gordon College",
	"Gordon State College",
	"Goshen College",
	"Goucher College",
	"Governors State University",
	"Grace College and Theological Seminary",
	"Graceland University at Independence",
	"Graceland University",
	"Grambling State University",
	"Grand Canyon University",
	"Grand Rapids Community College",
	"Grand Valley State University",
	"Grand View University",
	"Granite State College",
	"Grays Harbor College",
	"Grayson College",
	"Great Basin College",
	"Great Bay Community College",
	"Great Falls College Montana State University",
	"Great Lakes Christian College",
	"Green River College",
	"Greensboro College",
	"Greenville Technical College",
	"Greenville University",
	"Grinnell College",
	"Grove City College",
	"Guilford College",
	"Gulf Coast State College",
	"Gustavus Adolphus College",
	"Gwinnett Institute",
	"Gwynedd Mercy University",
	"HCI College at Fort Lauderdale",
	"HCI College",
	"Hamilton College",
	"Hamline University",
	"Hampden-Sydney College",
	"Hampshire College",
	"Hampton University",
	"Hanover College",
	"Hardin-Simmons University",
	"Harding University",
	"Harris-Stowe State University",
	"Hartwick College",
	"Harvard University",
	"Harvey Mudd College",
	"Haskell Indian Nations University",
	"Hastings College",
	"Haverford College",
	"Hawaii Pacific University",
	"Hawkeye Community College",
	"Hazard Community and Technical College",
	"Hebrew College",
	"Hebrew Union College-Jewish Institute of Religion",
	"Heidelberg University",
	"Helena College",
	"Helene Fuld College of Nursing",
	"Henderson Community College",
	"Henderson State University",
	"Hendrix College",
	"Hennepin Technical College",
	"Henry Ford College",
	"Herkimer County Community College",
	"Hesston College",
	"Hibbing Community College",
	"High Point University",
	"Highline College",
	"Hilbert College",
	"Hill College",
	"Hillsborough Community College",
	"Hillsdale College",
	"Hiram College",
	"Hobart William Smith Colleges",
	"Hofstra University",
	"Hollins University",
	"Holy Family University",
	"Holy Names University",
	"Hood College",
	"Hope College",
	"Hopkinsville Community College",
	"Houghton College",
	"Houston Baptist University",
	"Howard Payne University",
	"Howard University",
	"Hudson Valley Community College",
	"Humboldt State University",
	"Huntingdon College",
	"Husson University",
	"Hutchinson Community College",
	"Icahn School of Medicine at Mount Sinai",
	"Idaho State University",
	"Ilisagvik College",
	"Illinois College",
	"Illinois Institute of Technology",
	"Illinois State University",
	"Illinois Wesleyan University",
	"Immaculata University",
	"Immokalee Technical College",
	"Indian River State College",
	"Indiana State University",
	"Indiana University Bloomington",
	"Indiana University East",
	"Indiana University Kokomo",
	"Indiana University Northwest",
	"Indiana University South Bend",
	"Indiana University Southeast",
	"Indiana University of Pennsylvania",
	"Indiana University-Purdue University Indianapolis",
	"Institute of American Indian Arts",
	"Inver Hills Community College",
	"Iona College",
	"Iowa State University",
	"Iowa Wesleyan University",
	"Itasca Community College",
	"Ithaca College",
	"Ivy Tech Community College System",
	"Jackson College",
	"Jackson State Community College",
	"Jackson State University",
	"Jacksonville State University",
	"Jacksonville University",
	"James Madison University",
	"Jamestown Business College",
	"Jamestown Community College",
	"Jefferson Community College",
	"Jefferson Community and Technical College",
	"John Brown University",
	"John Carroll University",
	"Johns Hopkins University",
	"Johnson & Wales University",
	"Johnson & Wales University-Charlotte",
	"Johnson & Wales University-Denver",
	"Johnson & Wales University-North Miami",
	"Johnson C Smith University",
	"Johnson County Community College",
	"Juniata College",
	"Kalamazoo College",
	"Kansas City Art Institute",
	"Kansas State University",
	"Kansas Wesleyan University",
	"Kapiolani Community College",
	"Kaskaskia College",
	"Kean University",
	"Keene State College",
	"Keiser University Flagship",
	"Keiser University at Fort Myers",
	"Keiser University at Jacksonville",
	"Keiser University at Lakeland",
	"Keiser University at Melbourne",
	"Keiser University at Sarasota",
	"Keiser University at Tallahassee",
	"Keiser University at West Palm Beach",
	"Keiser University-Daytona",
	"Keiser University-Port St Lucie",
	"Kennesaw State University",
	"Kent State University Geauga Campus",
	"Kent State University at Ashtabula",
	"Kent State University at East Liverpool",
	"Kent State University at Salem",
	"Kent State University at Stark",
	"Kent State University at Trumbull",
	"Kent State University at Tuscarawas",
	"Kent State University",
	"Kentucky Christian University",
	"Kentucky State University",
	"Kentucky Wesleyan College",
	"Kenyon College",
	"Kettering University",
	"Keuka College",
	"Keystone College",
	"King University",
	"King's College",
	"Knox College",
	"Kutztown University",
	"Kuyper College",
	"La Roche University",
	"La Salle University",
	"LaGrange College",
	"Labette Community College",
	"Lafayette College",
	"Lake Erie College",
	"Lake Forest College",
	"Lake Land College",
	"Lake Michigan College",
	"Lake Region State College",
	"Lake Superior College",
	"Lake Superior State University",
	"Lake Technical College",
	"Lake Washington Institute of Technology",
	"Lake-Sumter State College",
	"Lakeland University",
	"Lakes Region Community College",
	"Lamar Community College",
	"Lamar University",
	"Lancaster Bible College",
	"Lander University",
	"Landmark College",
	"Lane College",
	"Lane Community College",
	"Langston University",
	"Laredo College",
	"Lasell University",
	"Lawrence Technological University",
	"Lawrence University",
	"Le Moyne College",
	"LeMoyne-Owen College",
	"LeTourneau University",
	"Lebanon Valley College",
	"Lee University",
	"Lees-McRae College",
	"Leeward Community College",
	"Lehigh University",
	"Lenoir-Rhyne University",
	"Lesley University",
	"Lewis & Clark College",
	"Lewis University",
	"Lewis-Clark State College",
	"Lexington Healing Arts Academy",
	"Lexington Theological Seminary",
	"Liberty University",
	"Limestone College",
	"Lincoln Memorial University",
	"Lincoln University of Missouri",
	"Lincoln University",
	"Lindenwood University",
	"Lindsey Hopkins Technical College",
	"Lindsey Wilson College",
	"Linfield University",
	"Linfield University-School of Nursing",
	"Lipscomb University",
	"Little Big Horn College",
	"Lively Technical College",
	"Livingstone College",
	"Lock Haven University",
	"Long Island Business Institute",
	"Long Island University",
	"Longwood University",
	"Lorain County Community College",
	"Loraines Academy & Spa",
	"Loras College",
	"Lorenzo Walker Technical College",
	"Los Angeles Community College District",
	"Louisiana College",
	"Louisiana Delta Community College",
	"Louisiana State University",
	"Louisiana Tech University",
	"Lourdes University",
	"Lower Columbia College",
	"Loyola Marymount University",
	"Loyola University Chicago",
	"Loyola University Maryland",
	"Loyola University New Orleans",
	"Lubbock Christian University",
	"Lurleen B. Wallace Community College",
	"Luther College",
	"Lycoming College",
	"Lynn University",
	"Lyon College",
	"Macalester College",
	"Madison Area Technical College",
	"Madisonville Community College",
	"Madonna University",
	"Magdalen College",
	"Maine Maritime Academy",
	"Malone University",
	"Manchester University",
	"Manhattan College",
	"Manhattanville College",
	"Mansfield University of Pennsylvania",
	"Maranatha Baptist University",
	"Maria College of Albany",
	"Marian University",
	"Marian University",
	"Marietta College",
	"Marion Military Institute",
	"Marion Technical College",
	"Marist College",
	"Marquette University",
	"Mars Hill University",
	"Marshall University",
	"Marshalltown Community College",
	"Martin Luther College",
	"Mary Baldwin University",
	"Marymount Manhattan College",
	"Marymount University",
	"Maryville College",
	"Maryville University Saint Louis",
	"Marywood University",
	"Massachusetts College of Art and Design",
	"Massachusetts College of Liberal Arts",
	"Massachusetts College of Pharmacy and Health Sciences",
	"Massachusetts Institute of Technology",
	"Massachusetts Maritime Academy",
	"Maysville Community and Technical College",
	"Mayville State University",
	"McDaniel College",
	"McKendree University",
	"McLennan Community College",
	"McMurry University",
	"McNeese State University",
	"MedQuest College",
	"Medaille College",
	"Medical University of South Carolina",
	"Menlo College",
	"Mercer University",
	"Mercy College",
	"Mercyhurst University",
	"Meredith College",
	"Meridian College",
	"Merrimack College",
	"Mesabi Range College",
	"Mesabi Range College",
	"Messiah University",
	"Methodist University",
	"Metropolitan College of New York",
	"Metropolitan State University of Denver",
	"Metropolitan State University",
	"Miami Dade College",
	"Miami International University of Art and Design",
	"Miami University (Ohio)",
	"Michigan State University",
	"Michigan Technological University",
	"Mid Michigan College",
	"Middle Georgia State University",
	"Middle Tennessee State University",
	"Middlebury College",
	"Midland College",
	"Midland University",
	"Midway University",
	"Midwestern State University",
	"Midwestern University at Downers Grove",
	"Midwestern University at Glendale",
	"Mildred Elley School-Albany Campus",
	"Mildred Elley-New York Campus",
	"Miles College",
	"Miles Community College",
	"Millersville University of Pennsylvania",
	"Milligan University",
	"Millikin University",
	"Mills College",
	"Millsaps College",
	"Milwaukee School of Engineering",
	"Minneapolis Community and Technical College",
	"Minnesota State College Southeast",
	"Minnesota State Community and Technical College",
	"Minnesota State University Moorhead",
	"Minnesota State University, Mankato",
	"Minnesota West Community and Technical College",
	"Minot State University",
	"MiraCosta College",
	"Misericordia University",
	"Mississippi College",
	"Mississippi Delta Community College",
	"Mississippi State University",
	"Mississippi University for Women",
	"Mississippi Valley State University",
	"Missouri Baptist University",
	"Missouri Southern State University",
	"Missouri State University",
	"Missouri University of Science and Technology",
	"Missouri Western State University",
	"Mitchell College",
	"Modesto Junior College",
	"Mohave Community College",
	"Mohawk Valley Community College",
	"Molloy College",
	"Monmouth College",
	"Monmouth University",
	"Monroe College",
	"Monroe Community College",
	"Montana Bible College",
	"Montana State University Billings",
	"Montana State University Northern",
	"Montana State University",
	"Montana Technological University",
	"Montclair State University",
	"Montreat College",
	"Moody Bible Institute",
	"Moravian College",
	"Morehead State University",
	"Morehouse College",
	"Morgan Community College",
	"Morgan State University",
	"Morningside College",
	"Motlow State Community College",
	"Mott Community College",
	"Mount Aloysius College",
	"Mount Holyoke College",
	"Mount Marty College",
	"Mount Mary University",
	"Mount Saint Joseph University",
	"Mount Saint Mary College",
	"Mount St. Mary's University",
	"Muhlenberg College",
	"Murray State University",
	"Muskingum University",
	"NHTI-Concord's Community College",
	"Nashua Community College",
	"Nashville State Community College",
	"Nassau Community College",
	"National Park College",
	"Navajo Technical University",
	"Naval Postgraduate School",
	"Nazareth College",
	"Nebraska Wesleyan University",
	"Neumann University",
	"Nevada State College",
	"New College of Florida",
	"New England College",
	"New Jersey City University",
	"New Jersey Institute of Technology",
	"New Mexico Highlands University",
	"New Mexico Institute of Mining and Technology",
	"New Mexico Military Institute",
	"New Mexico State University",
	"New Orleans Baptist Theological Seminary",
	"New York Automotive and Diesel Institute",
	"New York Chiropractic College",
	"New York College of Health Professions",
	"New York College of Podiatric Medicine",
	"New York College of Traditional Chinese Medicine",
	"New York Institute of Technology",
	"New York Law School",
	"New York Medical College",
	"New York School of Interior Design",
	"New York University",
	"Newberry College",
	"Newman University",
	"Niagara County Community College",
	"Niagara University",
	"Nicholls State University",
	"Nichols College",
	"Norfolk State University",
	"Normandale Community College",
	"North Arkansas College",
	"North Carolina A&T State University",
	"North Carolina Central University",
	"North Carolina State University",
	"North Carolina Wesleyan College",
	"North Central College",
	"North Central State College",
	"North Central University",
	"North Dakota State College of Science",
	"North Dakota State University",
	"North Florida College",
	"North Greenville University",
	"North Hennepin Community College",
	"North Idaho College",
	"North Park University",
	"North Seattle College",
	"NorthWest Arkansas Community College",
	"Northeast Mississippi Community College",
	"Northeast Ohio Medical University",
	"Northeast State Community College",
	"Northeastern Illinois University",
	"Northeastern Junior College",
	"Northeastern Seminary",
	"Northeastern State University",
	"Northeastern University",
	"Northern Arizona University",
	"Northern Illinois University",
	"Northern Kentucky University",
	"Northern Marianas College",
	"Northern Michigan University",
	"Northern New Mexico College",
	"Northern Oklahoma College",
	"Northern State University",
	"Northern Vermont University-Johnson",
	"Northern Vermont University-Lyndon",
	"Northland College",
	"Northland Community and Technical College",
	"Northshore Technical Community College",
	"Northwest Florida State College",
	"Northwest Indian College",
	"Northwest Louisiana Technical College",
	"Northwest Missouri State University",
	"Northwest Nazarene University",
	"Northwest Technical College",
	"Northwestern College",
	"Northwestern Michigan College",
	"Northwestern Oklahoma State University",
	"Northwestern State University of Louisiana",
	"Northwestern University",
	"Northwood University",
	"Norwich University",
	"Notre Dame College",
	"Notre Dame de Namur University",
	"Notre Dame of Maryland University",
	"Nouvelle Institute",
	"Nova Southeastern University",
	"Nueta Hidatsa Sahnish College",
	"Nunez Community College",
	"Nyack College",
	"Oakland City University",
	"Oakland University",
	"Oberlin College",
	"Occidental College",
	"Odessa College",
	"Oglala Lakota College",
	"Oglethorpe University",
	"Ohio Dominican University",
	"Ohio Northern University",
	"Ohio State University",
	"Ohio University",
	"Ohio University-Chillicothe",
	"Ohio University-Eastern",
	"Ohio University-Lancaster",
	"Ohio University-Southern",
	"Ohio University-Zanesville",
	"Ohio Valley University",
	"Ohio Wesleyan University",
	"Okaloosa Technical College",
	"Oklahoma Baptist University",
	"Oklahoma Christian University",
	"Oklahoma City University",
	"Oklahoma Panhandle State University",
	"Oklahoma State University Center for Health Sciences",
	"Oklahoma State University Institute of Technology",
	"Oklahoma State University",
	"Oklahoma State University-Oklahoma City",
	"Old Dominion University",
	"Olivet College",
	"Olivet Nazarene University",
	"Olympic College",
	"Onondaga Community College",
	"Oral Roberts University",
	"Orange County Community College",
	"Orange Technical College Mid Florida Campus",
	"Orange Technical College Orlando Campus",
	"Orange Technical College Westside Campus",
	"Orange Technical College Winter Park Campus",
	"Oregon Health & Science University",
	"Oregon Institute of Technology",
	"Oregon State University",
	"Oregon State University-Cascades",
	"Otero Junior College",
	"Otterbein University",
	"Ouachita Baptist University",
	"Owensboro Community and Technical College",
	"Ozarks Technical Community College",
	"Pace University",
	"Pacific College of Oriental Medicine",
	"Pacific Lutheran University",
	"Pacific University",
	"Palm Beach Atlantic University",
	"Palm Beach State College",
	"Parkland College",
	"Pasco-Hernando State College",
	"Paul Mitchell the School-Jacksonville",
	"Paul Mitchell the School-Lexington",
	"Paul Smiths College",
	"Pellissippi State Community College",
	"Peninsula College",
	"Penn State University",
	"Pennsylvania College of Technology",
	"Pensacola State College",
	"Pepperdine University",
	"Peru State College",
	"Pfeiffer University",
	"Piedmont College",
	"Pierce College",
	"Pikes Peak Community College",
	"Pima Medical Institute-Dillon",
	"Pine Manor College",
	"Pine Technical & Community College",
	"Pinellas Technical College-St. Petersburg",
	"Pittsburg State University",
	"Pitzer College",
	"Plaza College",
	"Plymouth State University",
	"Point Loma Nazarene University",
	"Point Park University",
	"Polk State College",
	"Pomona College",
	"Portland State University",
	"Post University",
	"Potomac State College of West Virginia University",
	"Prairie View A&M University",
	"Pratt Institute",
	"Praxis Institute",
	"Presbyterian College",
	"Princeton University",
	"Principia College",
	"Providence College",
	"Pueblo Community College",
	"Purdue University - Purdue Polytechnic Anderson",
	"Purdue University - Purdue Polytechnic Columbus",
	"Purdue University - Purdue Polytechnic Indianapolis",
	"Purdue University - Purdue Polytechnic Kokomo",
	"Purdue University - Purdue Polytechnic Lafayette",
	"Purdue University - Purdue Polytechnic New Albany",
	"Purdue University - Purdue Polytechnic Richmond",
	"Purdue University - Purdue Polytechnic South Bend",
	"Purdue University - Purdue Polytechnic Vincennes",
	"Purdue University Fort Wayne",
	"Purdue University Northwest",
	"Purdue University",
	"Queens University of Charlotte",
	"Quincy University",
	"Quinnipiac University",
	"Radford M Locklin Technical College",
	"Radford University",
	"Rainy River Community College",
	"Ramapo College of New Jersey",
	"Randolph College",
	"Randolph-Macon College",
	"Rasmussen College at Fort Myers",
	"Red Rocks Community College",
	"Reed College",
	"Regis College",
	"Regis University",
	"Rensselaer Polytechnic Institute",
	"Renton Technical College",
	"Rhode Island College",
	"Rhode Island School of Design",
	"Rhodes College",
	"Rice University",
	"Rider University",
	"Ridge Technical College",
	"Ridgewater College",
	"Rio Hondo College",
	"Ripon College",
	"River Parishes Community College",
	"River Valley Community College",
	"Riverland Community College",
	"Riveroak Technical College",
	"Rivier University",
	"Roane State Community College",
	"Roanoke College",
	"Robert Morris University",
	"Roberts Wesleyan College",
	"Rochester Community and Technical College",
	"Rochester Institute of Technology",
	"Rochester University",
	"Rockefeller University",
	"Rockford University",
	"Rockhurst University",
	"Rockland Community College",
	"Rocky Mountain College",
	"Roger Williams University",
	"Rogers State University",
	"Rollins College",
	"Rose State College",
	"Rose-Hulman Institute of Technology",
	"Rosemont College",
	"Rowan University",
	"Russell Sage College",
	"Rust College",
	"Rutgers University",
	"Rutgers University-Camden",
	"Rutgers University-Newark",
	"SOWELA Technical Community College",
	"SUNY Albany",
	"SUNY Alfred State College of Technology",
	"SUNY Binghamton",
	"SUNY Brockport",
	"SUNY Broome Community College",
	"SUNY Buffalo State",
	"SUNY Canton",
	"SUNY Cobleskill",
	"SUNY College at Potsdam",
	"SUNY College of Environmental Science and Forestry",
	"SUNY College of Optometry",
	"SUNY Corning Community College",
	"SUNY Cortland",
	"SUNY Delhi",
	"SUNY Downstate Health Sciences University",
	"SUNY Empire State College",
	"SUNY Geneseo",
	"SUNY Maritime College",
	"SUNY Morrisville",
	"SUNY New Paltz",
	"SUNY Old Westbury",
	"SUNY Oneonta",
	"SUNY Oswego",
	"SUNY Plattsburgh",
	"SUNY Polytechnic Institute",
	"SUNY Purchase College",
	"SUNY University at Buffalo",
	"SUNY Westchester Community College",
	"SUNY at Fredonia",
	"Sacred Heart University",
	"Saginaw Valley State University",
	"Saint Ambrose University",
	"Saint Anselm College",
	"Saint Augustine's University",
	"Saint Edward's University",
	"Saint Elizabeth College of Nursing",
	"Saint Elizabeth University",
	"Saint Francis University",
	"Saint Joseph Seminary College",
	"Saint Joseph's College of Maine",
	"Saint Joseph's University",
	"Saint Leo University",
	"Saint Louis University",
	"Saint Martin's University",
	"Saint Mary's College of California",
	"Saint Mary's College",
	"Saint Mary's University of Minnesota",
	"Saint Michael's College",
	"Saint Norbert College",
	"Saint Peter's University",
	"Saint Vincent College",
	"Saint Xavier University",
	"Salem College",
	"Salem State University",
	"Salem University",
	"Salisbury University",
	"Salish Kootenai College",
	"Salt Lake Community College",
	"Salve Regina University",
	"Sam Houston State University",
	"Samford University",
	"San Diego City College",
	"San Diego Mesa College",
	"San Diego Miramar College",
	"San Diego State University System",
	"San Francisco State University",
	"San Jose State University",
	"San Juan College",
	"Santa Ana College",
	"Santa Clara University",
	"Santa Fe College",
	"Santa Fe Community College",
	"Santa Monica College",
	"Santiago Canyon College",
	"Sarah Lawrence College",
	"Savannah State University",
	"Schenectady County Community College",
	"School of the Art Institute of Chicago",
	"Schoolcraft College",
	"Schreiner University",
	"Scripps College",
	"Seattle Central College",
	"Seattle Pacific University",
	"Seattle University",
	"Seminole State College of Florida",
	"Seton Hall University",
	"Seton Hill University",
	"Shasta College",
	"Shaw University",
	"Shawnee State University",
	"Shenandoah University",
	"Shepherd University",
	"Sheridan Technical College",
	"Shippensburg University of Pennsylvania",
	"Shorter University",
	"Siena College",
	"Siena Heights University",
	"Simmons College of Kentucky",
	"Simmons University",
	"Simpson College",
	"Sinclair Community College",
	"Sinte Gleska University",
	"Sitting Bull College",
	"Skagit Valley College",
	"Skidmore College",
	"Skyline College",
	"Slippery Rock University of Pennsylvania",
	"Smith College",
	"Snead State Community College",
	"Snow College",
	"Solano Community College",
	"Somerset Community College",
	"Sonoma State University",
	"Sotheby's Institute of Art",
	"South Arkansas Community College",
	"South Carolina State University",
	"South Central College",
	"South Dakota School of Mines and Technology",
	"South Dakota State University",
	"South Florida Bible College and Theological Seminary",
	"South Florida State College",
	"South Georgia State College",
	"South Louisiana Community College",
	"South Plains College",
	"South Seattle College",
	"South Texas College",
	"Southcentral Kentucky Community and Technical College",
	"Southeast Community College",
	"Southeast Kentucky Community and Technical College",
	"Southeast Missouri State University",
	"Southeastern College at West Palm Beach",
	"Southeastern Illinois College",
	"Southeastern Louisiana University",
	"Southeastern Oklahoma State University",
	"Southeastern University",
	"Southern Adventist University",
	"Southern Arkansas University",
	"Southern Connecticut State University",
	"Southern Illinois University Carbondale",
	"Southern Illinois University Edwardsville",
	"Southern Methodist University",
	"Southern Nazarene University",
	"Southern New Hampshire University",
	"Southern Oregon University",
	"Southern Union State Community College",
	"Southern University Law Center",
	"Southern University and A&M College",
	"Southern University at New Orleans",
	"Southern University at Shreveport",
	"Southern Utah University",
	"Southern Virginia University",
	"Southern Wesleyan University",
	"Southwest Baptist University",
	"Southwest Minnesota State University",
	"Southwest Tennessee Community College",
	"Southwestern College",
	"Southwestern College",
	"Southwestern Illinois College",
	"Southwestern Oklahoma State University",
	"Southwestern University",
	"Spalding University",
	"Spokane Community College",
	"Spokane Falls Community College",
	"Spring Arbor University",
	"Spring Hill College",
	"Springfield College",
	"St. Bonaventure University",
	"St. Catherine University",
	"St. Cloud State University",
	"St. Cloud Technical and Community College",
	"St. Francis College",
	"St. John Fisher College",
	"St. John's University",
	"St. Johns River State College",
	"St. Joseph School of Nursing",
	"St. Joseph's College Long Island",
	"St. Joseph's College New York",
	"St. Joseph's College of Nursing",
	"St. Lawrence University",
	"St. Louis College of Pharmacy",
	"St. Louis Community College",
	"St. Mary's College of Maryland",
	"St. Mary's University",
	"St. Olaf College",
	"St. Paul College",
	"St. Petersburg College",
	"St. Thomas Aquinas College",
	"St. Thomas University",
	"Stanford University",
	"State College of Florida, Manatee-Sarasota",
	"State Fair Community College",
	"Stephen F. Austin State University",
	"Stephens College",
	"Sterling College",
	"Sterling College",
	"Stetson University",
	"Stevens Institute of Technology",
	"Stevenson University",
	"Stockton University",
	"Stone Child College",
	"Stonehill College",
	"Stony Brook University",
	"Strayer University at Fort Lauderdale",
	"Suffolk County Community College",
	"Suffolk University",
	"Sul Ross State University",
	"Sullivan County Community College",
	"Sullivan University",
	"Suncoast Technical College",
	"Sunstate Academy-Jones Technical Institute",
	"Susquehanna University",
	"Swarthmore College",
	"Swedish Institute a College of Health Sciences",
	"Sweet Briar College",
	"Syracuse University",
	"Tacoma Community College",
	"Tallahassee Community College",
	"Tarleton State University",
	"Taylor University",
	"Teachers College of San Joaquin",
	"Temple University",
	"Tennessee College of Applied Technology",
	"Tennessee State University",
	"Tennessee Technological University",
	"Terra State Community College",
	"Texarkana College",
	"Texas A&M University",
	"Texas Christian University",
	"Texas College",
	"Texas Lutheran University",
	"Texas Southern University",
	"Texas State University",
	"Texas Tech University Health Sciences Center El Paso",
	"Texas Tech University Health Sciences Center",
	"Texas Tech University",
	"Texas Wesleyan University",
	"Texas Woman’s University",
	"The Citadel",
	"The College of New Jersey",
	"The College of Saint Rose",
	"The College of Saint Scholastica",
	"The College of Westchester",
	"The College of Wooster",
	"The College of the Florida Keys",
	"The Graduate Center, CUNY",
	"The King's College",
	"The New School",
	"The Southern Baptist Theological Seminary",
	"The University of Findlay",
	"The University of the South",
	"Thiel College",
	"Thomas College",
	"Thomas Edison State University",
	"Thomas Jefferson University",
	"Thomas More College of Liberal Arts",
	"Thomas More University",
	"Tiffin University",
	"Tompkins Cortland Community College",
	"Touro College",
	"Towson University",
	"Transylvania University",
	"Traviss Technical College",
	"Trevecca Nazarene University",
	"Tri-County Technical College",
	"Trine University",
	"Trinidad State Junior College",
	"Trinity College of Florida",
	"Trinity College",
	"Trinity University",
	"Trinity Washington University",
	"Trocaire College",
	"Troy University Dothan",
	"Troy University Montgomery",
	"Troy University Phenix City",
	"Troy University",
	"Truckee Meadows Community College",
	"Truman State University",
	"Tufts University",
	"Tulane University of Louisiana",
	"Tunxis Community College",
	"Tusculum University",
	"Tuskegee University",
	"Tyler Junior College",
	"Ulster County Community College",
	"Union College",
	"Union College",
	"Union University",
	"United States Air Force Academy",
	"United States Coast Guard Academy",
	"United States Merchant Marine Academy",
	"United States Military Academy West Point",
	"United States Naval Academy",
	"Universal Technical Institute Orlando",
	"University of Akron",
	"University of Alabama at Birmingham",
	"University of Alabama in Huntsville",
	"University of Alabama",
	"University of Alaska Anchorage",
	"University of Alaska Fairbanks",
	"University of Alaska Southeast",
	"University of Arizona",
	"University of Arkansas",
	"University of Arkansas-Pulaski Technical College",
	"University of Baltimore",
	"University of Bridgeport",
	"University of California, Berkeley",
	"University of California, Davis",
	"University of California, Hastings College of Law",
	"University of California, Irvine",
	"University of California, Los Angeles",
	"University of California, Merced",
	"University of California, Riverside",
	"University of California, San Diego",
	"University of California, San Francisco",
	"University of California, Santa Barbara",
	"University of California, Santa Cruz",
	"University of Central Arkansas",
	"University of Central Florida",
	"University of Central Missouri",
	"University of Central Oklahoma",
	"University of Charleston",
	"University of Chicago",
	"University of Cincinnati",
	"University of Colorado Boulder",
	"University of Colorado Colorado Springs",
	"University of Colorado Denver and Anschutz Medical Campus",
	"University of Connecticut",
	"University of Dallas",
	"University of Dayton",
	"University of Delaware",
	"University of Denver",
	"University of Detroit Mercy",
	"University of Dubuque",
	"University of Evansville",
	"University of Florida",
	"University of Fort Lauderdale",
	"University of Georgia",
	"University of Guam",
	"University of Hartford",
	"University of Hawaii Maui College",
	"University of Hawaii at Hilo",
	"University of Hawaii at Manoa",
	"University of Hawaii-West Oahu",
	"University of Holy Cross",
	"University of Houston",
	"University of Idaho",
	"University of Illinois Springfield",
	"University of Illinois Urbana-Champaign",
	"University of Illinois at Chicago",
	"University of Indianapolis",
	"University of Iowa",
	"University of Kansas",
	"University of Kentucky",
	"University of La Verne",
	"University of Louisiana Monroe",
	"University of Louisiana at Lafayette",
	"University of Louisville",
	"University of Lynchburg",
	"University of Maine Farmington",
	"University of Maine at Augusta",
	"University of Maine at Fort Kent",
	"University of Maine at Machias",
	"University of Maine at Presque Isle",
	"University of Maine",
	"University of Mary Hardin at Baylor",
	"University of Mary Washington",
	"University of Mary",
	"University of Maryland Eastern Shore",
	"University of Maryland, Baltimore County",
	"University of Maryland, Baltimore",
	"University of Maryland, College Park",
	"University of Massachusetts Amherst",
	"University of Massachusetts Boston",
	"University of Massachusetts Dartmouth",
	"University of Massachusetts Lowell",
	"University of Massachusetts Medical School",
	"University of Memphis",
	"University of Miami",
	"University of Michigan",
	"University of Michigan-Dearborn",
	"University of Michigan-Flint",
	"University of Minnesota Crookston",
	"University of Minnesota Duluth",
	"University of Minnesota Morris",
	"University of Minnesota Rochester",
	"University of Minnesota Twin Cities",
	"University of Mississippi Medical Center",
	"University of Mississippi",
	"University of Missouri",
	"University of Missouri-Kansas City",
	"University of Missouri-St. Louis",
	"University of Montana Western",
	"University of Montana",
	"University of Montevallo",
	"University of Mount Olive",
	"University of Mount Union",
	"University of Nebraska Medical Center",
	"University of Nebraska at Kearney",
	"University of Nebraska at Omaha",
	"University of Nebraska-Lincoln",
	"University of Nevada, Las Vegas",
	"University of Nevada, Reno",
	"University of New England",
	"University of New Hampshire",
	"University of New Haven",
	"University of New Mexico",
	"University of New Orleans",
	"University of North Alabama",
	"University of North Carolina Asheville",
	"University of North Carolina School of the Arts",
	"University of North Carolina Wilmington",
	"University of North Carolina at Chapel Hill",
	"University of North Carolina at Charlotte",
	"University of North Carolina at Greensboro",
	"University of North Carolina at Pembroke",
	"University of North Dakota",
	"University of North Florida",
	"University of North Georgia",
	"University of North Texas Health Science Center",
	"University of North Texas at Dallas",
	"University of North Texas",
	"University of Northern Colorado",
	"University of Northern Iowa",
	"University of Northwestern, St. Paul",
	"University of Notre Dame",
	"University of Oklahoma",
	"University of Oregon",
	"University of Pennsylvania",
	"University of Pikeville",
	"University of Pittsburgh Johnstown",
	"University of Pittsburgh at Bradford",
	"University of Pittsburgh at Greensburg",
	"University of Pittsburgh",
	"University of Portland",
	"University of Puerto Rico",
	"University of Puget Sound",
	"University of Redlands",
	"University of Rhode Island",
	"University of Richmond",
	"University of Rochester",
	"University of Saint Joseph",
	"University of Saint Mary",
	"University of San Diego",
	"University of San Francisco",
	"University of Science and Arts of Oklahoma",
	"University of Scranton",
	"University of Sioux Falls",
	"University of South Alabama",
	"University of South Carolina Aiken",
	"University of South Carolina Beaufort",
	"University of South Carolina Upstate",
	"University of South Carolina",
	"University of South Dakota",
	"University of South Florida Sarasota-Manatee",
	"University of South Florida St. Petersburg",
	"University of South Florida",
	"University of Southern California",
	"University of Southern Indiana",
	"University of Southern Maine",
	"University of Southern Mississippi",
	"University of St. Thomas",
	"University of St. Thomas",
	"University of Tampa",
	"University of Tennessee Health Science Center",
	"University of Tennessee at Chattanooga",
	"University of Tennessee at Martin",
	"University of Tennessee, Knoxville",
	"University of Texas",
	"University of Toledo",
	"University of Tulsa",
	"University of Utah",
	"University of Valley Forge",
	"University of Vermont",
	"University of Virginia",
	"University of Virginia's College at Wise",
	"University of Washington Bothell",
	"University of Washington Tacoma",
	"University of Washington",
	"University of West Alabama",
	"University of West Florida",
	"University of West Georgia",
	"University of Wisconsin",
	"University of Wyoming",
	"University of the Cumberlands",
	"University of the District of Columbia",
	"University of the Incarnate Word",
	"University of the Ozarks",
	"University of the Pacific",
	"University of the Sciences",
	"University of the Virgin Islands",
	"Upper Iowa University",
	"Upper Valley Educators Institute",
	"Upstate Medical University",
	"Ursinus College",
	"Ursuline College",
	"Utah State University",
	"Utah Valley University",
	"Utica College",
	"Valdosta State University",
	"Valencia College",
	"Valley City State University",
	"Valparaiso University",
	"Vanderbilt University",
	"Vassar College",
	"Vaughn College of Aeronautics and Technology",
	"Vermilion Community College",
	"Vermont College of Fine Arts",
	"Vermont Law School",
	"Vermont Technical College",
	"Villa Maria College",
	"Villanova University",
	"Vincennes University",
	"Virginia Commonwealth University",
	"Virginia Highlands Community College",
	"Virginia Military Institute",
	"Virginia State University",
	"Virginia Tech",
	"Virginia Union University",
	"Virginia Wesleyan University",
	"Viterbo University",
	"Volunteer State Community College",
	"Wabash College",
	"Wagner College",
	"Wake Forest University",
	"Wake Technical Community College",
	"Walla Walla Community College",
	"Walsh University",
	"Walters State Community College",
	"Warner University",
	"Warren Wilson College",
	"Wartburg College",
	"Washburn University",
	"Washington & Jefferson College",
	"Washington College",
	"Washington State University",
	"Washington University in St. Louis",
	"Washington and Lee University",
	"Washtenaw Community College",
	"Wayland Baptist University",
	"Wayne State College",
	"Wayne State University",
	"Waynesburg University",
	"Webb Institute",
	"Webber International University",
	"Weber State University",
	"Webster University",
	"Weill Cornell Medical College",
	"Wellesley College",
	"Wells College",
	"Wenatchee Valley College",
	"Wentworth Institute of Technology",
	"Wesley College",
	"Wesleyan College",
	"Wesleyan University",
	"West Chester University",
	"West Kentucky Community and Technical College",
	"West Liberty University",
	"West Texas A&M University",
	"West Virginia School of Osteopathic Medicine",
	"West Virginia State University",
	"West Virginia University Institute of Technology",
	"West Virginia University at Parkersburg",
	"West Virginia University",
	"West Virginia Wesleyan College",
	"Western Carolina University",
	"Western Colorado University",
	"Western Connecticut State University",
	"Western Illinois University",
	"Western Kentucky University",
	"Western Michigan University",
	"Western Nevada College",
	"Western New England University",
	"Western New Mexico University",
	"Western Oregon University",
	"Western Washington University",
	"Western Wyoming Community College",
	"Westfield State University",
	"Westminster College",
	"Westminster College",
	"Westminster College",
	"Westmont College",
	"Whatcom Community College",
	"Wheaton College",
	"Wheaton College",
	"Wheeling University",
	"White Mountains Community College",
	"Whitman College",
	"Whittier College",
	"Whitworth University",
	"Wichita State University",
	"Widener University",
	"Wilkes University",
	"Willamette University",
	"William & Mary",
	"William Jewell College",
	"William Paterson University",
	"William Peace University",
	"William Penn University",
	"William T. McFatter Technical College",
	"William Woods University",
	"Williams College",
	"Williston State College",
	"Wilmington College",
	"Wilmington University",
	"Wilson College",
	"Wingate University",
	"Winona State University",
	"Winston-Salem State University",
	"Winthrop University",
	"Wisconsin Lutheran College",
	"Withlacoochee Technical College",
	"Wittenberg University",
	"Wofford College",
	"Worcester Polytechnic Institute",
	"Worcester State University",
	"Word of Life Bible Institute",
	"Wright State University",
	"Wright State University-Lake Campus",
	"Xavier University of Louisiana",
	"Xavier University",
	"Yakima Valley College",
	"Yale University",
	"Yeshiva University",
	"York College of Pennsylvania",
	"Young Harris College",
	"Youngstown State University",
];
